### ISSUE TITLE
Yeoman installs fine, doctor says all is good to go, but installing generators breaks it :(

### ISSUE THREAD

**Issue by justjoolz** [yeoman/yeoman#1371]
I'm trying to get this setup on Linux Mint

I've been searching and trying every solution I've found on the web but none of the fixes seems to be working.

```
yo --version && echo $PATH $NODE_PATH &&      node -e 'console.log(process.platform, process.versions)' && cat Gruntfile.js
```

give me the following:

```
1.2.0
/home/j00lz/local/bin:/home/j00lz/.nvm/v0.11.13/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games :/home/j00lz/npm/lib    /node_modules:/usr/lib/node_modules:/usr/local/lib/node_modules
linux { http_parser: '2.2',
  node: '0.11.13',
  v8: '3.25.30',
  uv: '0.11.25',
  zlib: '1.2.3',
  modules: '14',
  openssl: '1.0.1g' }
cat: Gruntfile.js: No such file or directory
```

and when I try and install a generator I get this:

```
    /usr/local/lib/node_modules/yo/node_modules/update-notifier/node_modules/configstore/configstore.js:    73
            throw err;
                  ^
Error: EACCES, permission denied '/home/j00lz/.config/configstore/update-notifier-generator-angular.yml'
    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:443:18)
    at Object.fs.writeFileSync (evalmachine.<anonymous>:989:15)
    at Object.create.all.set (/usr/local/lib/node_modules/yo/node_modules/update-notifier/node_modules/configstore/configstore.js:63:8)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/update-notifier/node_modules/configstore/configstore.js:26:11)
    at new UpdateNotifier (/usr/local/lib/node_modules/yo/node_modules/update-notifier/lib/update-notifier.js:33:17)
    at module.exports (/usr/local/lib/node_modules/yo/node_modules/update-notifier/lib/update-notifier.js:146:23)
    at yoyo.resolveGenerators (/usr/local/lib/node_modules/yo/yoyo.js:277:18)
    at /usr/local/lib/node_modules/yo/node_modules/lodash/dist/lodash.js:901:23
    at forOwn (/usr/local/lib/node_modules/yo/node_modules/lodash/dist/lodash.js:2105:15)
```

Any help on this would be most appreciated I've been trying this on and off for days now!

**Comment by cybibo** [comment]
ls ~/.config/configstore
ls: /Users/ryan/.config/configstore: No such file or directory
