### ISSUE TITLE
Cannot find module after Generator execution

### ISSUE THREAD

**Issue by stephanfriedrich** [yeoman/yeoman#1424]
Hy,
i tried to install a Generator "Kickstart" on my Ubuntu Linux 14.10.
After successful installation of Yo, i run yo Kickstart but i got an error.

node:
-v =>  v0.10.31
-which => /opt/node/bin/node
npm:
-v => 1.4.23
which =>  /opt/node/bin/npm

/opt/node/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:8934
                throw e;
                      ^
Error: Cannot find module './lib/env'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/node/lib/node_modules/generator-kickstart/node_modules/yeoman-generator/main.js:8:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by koistya** [comment]
I'm having this issue:

```
> yo generator
module.js:334
    throw err;
          ^
Error: Cannot find module 'balanced-match'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\<User>\AppData\Roaming\npm\node_modules\generator-generator\node_modules\yeoman-generator\node_modules\yeoman-environment\node_modules\globby\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion\index.js:2:16)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
```

```
node v2.3.0, npm v2.11.3, yo v1.4.7, generator-generator v0.8.1
```
