### ISSUE TITLE
Cannot find module 'yeoman-generator'

### ISSUE THREAD

**Issue by iDuuck** [yeoman/yeoman#1464]
Hey guys,
I didn't know what I did wrong, but as of yesterday (I didn't use yeoman for a while now) the following error just occurs on every `yo [generator-name]` command.

```
Cannot find module 'yeoman-generator'
```

Don't know what to do now. I tried to remove and re-install yo, but didn't work (Awkward, because after the re-install, Yeoman said there was an update available, but I just installed the newest version). So is there any solution for this?

**UPDATE:** The full error message is the following:

```
Error: Cannot find module 'yeoman-generator'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-angular-fullstack/app/index.js:6:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by sindresorhus** [comment]
https://www.google.no/search?q=npm+Error%3A+Cannot+find+module

**Comment by kjellski** [comment]
I've been using nvm and this screwed me too.

This applies when your `echo $NODE_PATH` is suddenly emtpy.

Put the actual node path for your current nvm installed version in your .zshrc/.bashrc/.*rc:
    export NODE_PATH="$HOME/.nvm/`nvm current | sed -e 's/current\:[[:space:]]*//'`"
