### ISSUE TITLE
running error: can't find module `rx`

### ISSUE THREAD

**Issue by DrakeLeung** [yeoman/yeoman#1492]
```
node v0.12.0
yo v1.4.6
npm v2.70
```
When I run `yo`, and I would get the following error.

It seems `rx` package's error, cuz when I change the `rx` to older version(like `v2.4.0`) and I wouldn't get the error.
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'rx'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/drake/.node/lib/node_modules/yo/node_modules/inquirer/lib/ui/prompt.js:6:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by sindresorhus** [comment]
Seems like you had an npm install error. Try upgrading to latest npm and reinstall

npm support: https://github.com/npm/npm/issues

**Comment by squarejaw** [comment]
Might be related to this:
https://github.com/Reactive-Extensions/RxJS/issues/621
