### ISSUE TITLE
remote.directory() fatal error with Grunt files containing variables

### ISSUE THREAD

**Issue by davetgreen** [yeoman/yeoman#1530]
I'm building a generator that is pulling down various component parts of a framework I'm rolling, and it appears that whenever I try to use remote.directory() to pull down the Grunt component, it's actually parsing the files somehow rather than just copying them - which is leading to a fatal error due to the fact I'm using variables throughout.

I'm using this:

``````
// Grunt
this.remote('mkdo', 'kapow-grunt', 'master', function(err, remote) {
  if (!err) {
    remote.bulkDirectory('grunt', 'grunt');
    self.log(successColour('Successfully downloaded Kapow! Grunt'));
  } else {
    self.log(alertColour('\n Failed to download Kapow! Grunt'));
  }
});
``````
....and getting this...

````
/Users/davetgreen/Vagrant/www/kapow-yeoman/generator-kapow/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:236
  throw err;
        ^
ReferenceError: /Users/davetgreen/.cache/yeoman/mkdo/kapow-grunt/master/grunt/clean.js:4
    2|   scripts: {
    3|     src: [
 >> 4|     '<%= wpInfo.wp_content %>/themes/<%= wpInfo.theme_name %>/<%= wpInfo.js_dir %>/*.js',
    5|     '!<%= wpInfo.wp_content %>/themes/<%= wpInfo.theme_name %>/<%= wpInfo.js_dir %>/*.min.js'
    6|     ]
    7|   }

wpInfo is not defined
    at eval (eval at <anonymous> (/Users/davetgreen/Vagrant/www/kapow-yeoman/generator-kapow/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:460:12), <anonymous>:11:23)
    at returnedFn (/Users/davetgreen/Vagrant/www/kapow-yeoman/generator-kapow/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:489:17)
    at Object.exports.render (/Users/davetgreen/Vagrant/www/kapow-yeoman/generator-kapow/node_modules/yeoman-generator/node_modules/mem-fs-editor/node_modules/ejs/lib/ejs.js:315:37)
    at copy.process (/Users/davetgreen/Vagrant/www/kapow-yeoman/generator-kapow/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:18:18)
    at applyProcessingFunc (/Users/davetgreen/Vagrant/www/kapow-yeoman/generator-kapow/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/Users/davetgreen/Vagrant/www/kapow-yeoman/generator-kapow/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:56:24)
    at EditionInterface.exports.copy (/Users/davetgreen/Vagrant/www/kapow-yeoman/generator-kapow/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/davetgreen/Vagrant/www/kapow-yeoman/generator-kapow/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy-tpl.js:16:8)
    at template (/Users/davetgreen/Vagrant/www/kapow-yeoman/generator-kapow/node_modules/yeoman-generator/lib/actions/actions.js:134:11)
    at copy (/Users/davetgreen/Vagrant/www/kapow-yeoman/generator-kapow/node_modules/yeoman-generator/lib/actions/actions.js:43:10)
````

If I use bulkDirectory, everything works fine, but I'd prefer not to given that the Yeoman docs discourage it. Any thoughts? I would have thought it would just copy without bothering about the contents?

**Comment by SBoudrias** [comment]
Please use the new file helpers. http://yeoman.io/authoring/file-system.html

Otherwise, you need to replace your Grunt templates tags with `<%%` rather than `<%`
