### ISSUE TITLE
Windows path too long

### ISSUE THREAD

**Issue by pjquinn** [yeoman/yeoman#1532]
I love the idea of scaffolding, but it looks like many, many Windows users are beating their heads against this issue, along with other [node-gyp issues](https://github.com/TooTallNate/node-gyp/issues/629)

I've spent a bunch of hours on stackoverflow and the google today unsuccessfully trying to find a solution. Installed about 20 GB of MS Visual Studio with C++, no help.

Windows 8.1 / Cygwin (but also tried Cmder with exact same result). Everything else installs successfully. 

1.4.7
%PATH% %NODE_PATH%
win32 { http_parser: '2.3',
  node: '0.12.5',
  v8: '3.28.71.19',
  uv: '1.6.1',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1o' }
-bash: type: Gruntfile.js: not found

````
> utf-8-validate@1.1.0 install C:\wamp\www\learnyo\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


C:\wamp\www\learnyo\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(403,5): error MSB3191:
````
 **Unable to create directory "Release\obj\validation\validation.tlog\". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters**.

```` [C:\wamp\www\learnyo\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj]

gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\wamp\www\learnyo\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 

> bufferutil@1.1.0 install C:\wamp\www\learnyo\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

C:\wamp\www\learnyo\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(312,5): error MSB3491: Could not write lines to file "Release\obj\bufferutil\bufferutil.tlog\bufferutil.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\wamp\www\learnyo\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj]

gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\wamp\www\learnyo\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

````

Any ideas on getting this to work on Windows 7/8/10?
Could you guys maybe limit the depth of node_module nesting somehow?
 Many Thx.

**Comment by sindresorhus** [comment]
Nothing we can do about that. Try installing npm@3, as it reduces the nesting considerably. Though, the real fix is using a real OS like Ubuntu.

**Comment by pjquinn** [comment]
Why not just put DOES NOT WORK ON WINDOWS on the main Yeoman site and save everybody a lot of trouble?

**Comment by sindresorhus** [comment]
Yeoman works fine on Windows. The problem is with one of the dependencies of the generator you used. That is out of our control.
