### ISSUE TITLE
Cannot find module './dist/rx

### ISSUE THREAD

**Issue by yogieputra8** [yeoman/yeoman#1538]
Hello,
So I tried do "yo" command in Ubuntu 14.04 x64. and Got this message error? 
```
? 'Allo Jonathan! What would you like to do? Angular

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo angular


     _-----_
    |       |    .--------------------------.
    |--(o)--|    |    Welcome to Yeoman,    |
   `---------´   |   ladies and gentlemen!  |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Out of the box I include Bootstrap and some AngularJS recommended modules.

? Would you like to use Sass (with Compass)? No
? Would you like to include Bootstrap? Yes
? Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-resource.js, angular-route.js, angular-sanitize.js, angular-touch.js
identical app/styles/main.css
identical app/index.html
identical bower.json
identical .bowerrc
identical package.json
identical Gruntfile.js
identical README.md
   invoke   angular:common:/usr/lib/node_modules/generator-angular/app/index.js
identical     .editorconfig
identical     .gitattributes
identical     .jshintrc
identical     .yo-rc.json
identical     .gitignore
identical     test/.jshintrc
identical     app/.buildignore
identical     app/.htaccess
identical     app/404.html
identical     app/favicon.ico
identical     app/robots.txt
identical     app/views/main.html
identical     app/images/yeoman.png
   invoke   angular:main:/usr/lib/node_modules/generator-angular/app/index.js
identical     app/scripts/app.js
   invoke   angular:controller:/usr/lib/node_modules/generator-angular/app/index.js
identical     app/scripts/controllers/main.js
identical     test/spec/controllers/main.js

     _-----_
    |       |    .-----------------------.
    |--(o)--|    |      Bye from us!     |
   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /___A___\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   __'.___.'__   
 ´   `  |° ´ Y ` 

module.js:338
    throw err;
    ^
Error: Cannot find module './dist/rx'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/node_modules/generator-karma/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/index.js:1:72)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

What should I do to fix this?
I am using npm 2.11.3, node 0.12.7, yo 1.4.7, grunt-cli v0.1.13.

**Comment by SBoudrias** [comment]
This looks like an installation issue. Uninstall/reinstall and make sure you're trying with the latest npm, you're 3 minor version behind currently.
