### ISSUE TITLE
Error: EACCES, permission denied '/root/mytodo/app'

### ISSUE THREAD

**Issue by yogieputra8** [yeoman/yeoman#1539]
So, I make a new Directory, cd in it and try yo command and get this message error:

```
? ==========================================================================
We're constantly looking for ways to make yo better! 
May we anonymously report usage statistics to improve the tool over time? 
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== Yes
? 'Allo root! What would you like to do? Angular

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo angular


     _-----_
    |       |    .--------------------------.
    |--(o)--|    |    Welcome to Yeoman,    |
   `---------´   |   ladies and gentlemen!  |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Out of the box I include Bootstrap and some AngularJS recommended modules.

? Would you like to use Sass (with Compass)? No
? Would you like to include Bootstrap? Yes
? Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-resource.js, angular-route.js, angular-sanitize.js, angular-touch.js
   create app/styles/main.css

     _-----_
    |       |    .-----------------------.
    |--(o)--|    |      Bye from us!     |
   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /___A___\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   __'.___.'__   
 ´   `  |° ´ Y ` 

/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/mkdirp/index.js:74
                    throw err0;
                          ^
Error: EACCES, permission denied '/root/mytodo/app'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at sync (/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/mkdirp/index.js:55:12)
    at Function.sync (/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/mkdirp/index.js:61:24)
    at Generator.<anonymous> (/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/lib/actions/actions.js:106:12)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```
How to fix this issue?
I'm using Ubuntu 14. yo 1.4.8 + grunt v0.1.13 + bower 1.5.2 + npm 2.11.3 + nodejs v0.12.7

**Comment by SBoudrias** [comment]
Google for `chmod`.
