### ISSUE TITLE
Error: EACCES, permission denied 'bower.json'

### ISSUE THREAD

**Issue by yogieputra8** [yeoman/yeoman#1540]
So, I try yo command and got this message error?
I have tried ```chmod -R 777``` , ```chmod g+rwx /root /root/mytodo/bower.json``` . But still no luck

```
root@AMRSEVIEW:~/mytodo# yo
? 'Allo root! What would you like to do? Angular

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo angular


     _-----_
    |       |    .--------------------------.
    |--(o)--|    |    Welcome to Yeoman,    |
   `---------´   |   ladies and gentlemen!  |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Out of the box I include Bootstrap and some AngularJS recommended modules.

? Would you like to use Sass (with Compass)? No
? Would you like to include Bootstrap? Yes
? Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-resource.js, angular-route.js, angular-sanitize.js, angular-touch.js
identical app/styles/main.css
identical app/index.html
   create bower.json

     _-----_
    |       |    .-----------------------.
    |--(o)--|    |      Bye from us!     |
   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /___A___\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   __'.___.'__   
 ´   `  |° ´ Y ` 

fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: EACCES, permission denied 'bower.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at Generator.<anonymous> (/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/lib/actions/actions.js:217:10)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```
I want to chmod for bower.json but how to do that even bower.json still not exist yet.
What should I do to fix this issue? Sorry for the noobz question

**Comment by sindresorhus** [comment]
You're running as root and `yo` don't have permission to do anything. Run as a normal user instead. In the future please use StackOverflow for support questions.

https://www.google.com/search?q=Error%3A+EACCES%2C+permission+denied+%27bower.json%27&oq=Error%3A+EACCES%2C+permission+denied+%27bower.json%27&aqs=chrome..69i57j69i58j69i61.149j0j1&sourceid=chrome&es_sm=91&ie=UTF-8

**Comment by yogieputra8** [comment]
@sindresorhus ah, thanks for the explanation!
