### ISSUE TITLE
Yeoman failing Windows 10 / Git Bash 

### ISSUE THREAD

**Issue by phil-pedruco** [yeoman/yeoman#1555]
Try to follow the codelab tutorial on a Windows 10 machine using GitBash but Yeoman is falling over. When I call  Yeoman from the prompt it fails with the following.  I am able to call Yeoman from the Command Prompt.  

    C:\nodejs\node_modules\yo\node_modules\rx-lite\rx.lite.js:549
    throw e;
    ^

    TypeError: Cannot read property 'substring' of undefined
    at Interface.rl._getCursorPos (C:\nodejs\node_modules\yo\nodene2\index.js:55:51)
    at ScreenManager.render (C:\nodejs\node_modules\yo\node_modul\utils\screen      manager.js:19:27)
    at Prompt.render (C:\nodejs\node_modules\yo\node_modules\inqus\list.js:102:15)
    at Prompt._run (C:\nodejs\node_modules\yo\node_modules\inquirlist.js:73:8)
    at Prompt.run (C:\nodejs\node_modules\yo\node_modules\inquirease.js:57:8)
    at Object.<anonymous> (C:\nodejs\node_modules\yo\node_modulesi\prompt.js:83:12)
    at module.exports (C:\nodejs\node_modules\yo\node_modules\run:15:21)
    at C:\nodejs\node_modules\yo\node_modules\inquirer\lib\utils\
    at tryCatcher (C:\nodejs\node_modules\yo\node_modules\rx-lite:29)
    at setDisposable (C:\nodejs\node_modules\yo\node_modules\rx-l5380:36)

The set up is

    $ yo --version && echo %PATH% %NODE_PATH% && node -e "console.logrm, process.versions)" && type Gruntfile.js
    1.4.8
    %PATH% %NODE_PATH%
    win32 { http_parser: '2.5.0',
    node: '4.2.1',
    v8: '4.5.103.35',
    uv: '1.7.5',
    zlib: '1.2.8',
    ares: '1.10.1-DEV',
    icu: '56.1',
    modules: '46',
    openssl: '1.0.2d' }
    bash: type: Gruntfile.js: not found

**Comment by kevva** [comment]
https://github.com/SBoudrias/Inquirer.js/issues/272
