### ISSUE TITLE
useref.assets: undefined is not a function

### ISSUE THREAD

**Issue by crabicode** [yeoman/yeoman#1561]
`$.useref.assets` raises error just right after I generated through `yo angular --coffee`

node, npm are in the %PATH%

```
win32 { http_parser: '2.3',
  node: '0.12.7',
  v8: '3.28.71.19',
  uv: '1.6.1',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1p' }
```

`$.useref.assets` - undefined

```
gulp.task('client:build', ['html', 'styles'], function () {
  var jsFilter = $.filter('**/*.js');
  var cssFilter = $.filter('**/*.css');

  return gulp.src(paths.views.main)
    .pipe($.useref.assets({searchPath: [yeoman.app, '.tmp']}))
```

```
[10:51:29] 'client:build' errored after 672 ms
[10:51:29] TypeError: undefined is not a function
  at Gulp.<anonymous> (C:\Users\user\Desktop\app\gulpfile.js:180:20)
  at module.exports (C:\Users\user\Desktop\app\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
  at Gulp.Orchestrator._runTask (C:\Users\user\Desktop\app\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
  at Gulp.Orchestrator._runStep (C:\Users\user\Desktop\app\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
  at C:\Users\user\Desktop\app\node_modules\gulp\node_modules\orchestrator\index.js:279:18
  at finish (C:\Users\user\Desktop\app\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
  at C:\Users\user\Desktop\app\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:52:4
  at f (C:\Users\user\Desktop\app\node_modules\gulp\node_modules\orchestrator\node_modules\end-of-stream\node_modules\once\once.js:17:25)
  at DestroyableTransform.onend (C:\Users\user\Desktop\app\node_modules\gulp\node_modules\orchestrator\node_modules\end-of-stream\index.js:31:18)
  at DestroyableTransform.emit (events.js:129:20)
  at C:\Users\user\Desktop\app\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16

  at process._tickCallback (node.js:355:11)
```

**Comment by SBoudrias** [comment]
Issues with generator-angular should be opened on their repository.
