### ISSUE TITLE
yo doctor eaccess error

### ISSUE THREAD

**Issue by nathansabo** [yeoman/yeoman#1568]
Design-1:~ Nathan.Sabo$ yo doctor
/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/Users/Nathan.Sabo/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.create.all.get (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:130:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)

**Comment by nathansabo** [comment]
I'm not familiar … I was looking for a more specific answer.

**Comment by nathansabo** [comment]
Hi Simon,
I’m not real familiar with the command line or chmod. I was looking for a more specific answer. Any chance you could link to or provide one? Thanks for your help!

NATHAN SABO
Corporate Art Director

P: 828-255-0012, ext. 135
F: 828-255-0442
One Page Ave, Suite 280
Asheville, NC 28801
contactdd.com<http://www.contactdd.com>

[cid:1E1D4D8C-012F-40D9-9BE2-FA6F9D2CB855]

**Comment by SBoudrias** [comment]
The issue is that your user is not allowed to write to some file; thus the `permission denied`. So you need to change the permissions of these files to make it work.

You're running on a Unix system, you'll run into a LOT of permission issue. Better learn now how your system works, you'll save a lot of time going on.

**Comment by nathansabo** [comment]
Yes, it's OS X. The strange and frustrating thing is, a coworker on the same OS is having no issues doing the same thing I'm attempting to do. Do you know of a good resource where I could find some direction to resolve these permission issues?

**Comment by SBoudrias** [comment]
@nathansabo usually you don't run into these issues. I'm almost certain at some point you ran some command using `sudo` - and that messed up the game for you.

The take away? Never - ever - use `sudo`. If you need to use sudo, then you did something wrong and you should your permissions rather than making the issue worse.
