### ISSUE TITLE
Cannot find module 'yeoman-environment'

### ISSUE THREAD

**Issue by salah-saleh** [yeoman/yeoman#1569]
I run to this error when I try and run yo polymer:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'yeoman-environment'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-polymer/node_modules/yeoman-generator/index.js:7:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```
yo --version returns 1.5.0, node --version v4.2.2, npm --version 3.4.1, bower --version 1.6.5, grunt --version grunt-cli v0.1.13

I updated my polymer generator:
```
/Users/sam/.nvm/versions/node/v4.2.2/lib
└── generator-polymer@1.2.6
```
yo --version && echo $PATH $NODE_PATH && node -e 'console.log(process.platform, process.versions)' && cat Gruntfile.js:
```
/Users/sam/.nvm/versions/node/v4.2.2/bin:/usr/local/heroku/bin:/Users/sam/.rvm/gems/ruby-2.2.0/bin:/Users/sam/.rvm/gems/ruby-2.2.0@global/bin:/Users/sam/.rvm/rubies/ruby-2.2.0/bin:/usr/local/Cellar/gcc49/4.9.2_1/bin/:/usr/local/bin:/usr/local/bin:/Users/sam/google-cloud-sdk/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/texbin:/Users/sam/google-cloud-sdk/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/texbin:/Users/sam/google-cloud-sdk/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/texbin:/usr/local/grace/bin:/Library/Ruby/Gems/2.0.0:/Users/sam/.gem/ruby/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0:/Users/sam/.rvm/bin
darwin { http_parser: '2.5.0',
  node: '4.2.2',
  v8: '4.5.103.35',
  uv: '1.7.5',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2d' }
cat: Gruntfile.js: No such file or directory
```

```
which npm
/Users/sam/.nvm/versions/node/v4.2.2/bin/npm
test|⇒ which yo
/usr/local/bin/yo
test|⇒ which node
/Users/sam/.nvm/versions/node/v4.2.2/bin/node
```
I know the issue have been reported before but it said it is a problem with npm version, my npm version is up to date.

**Comment by arthurvr** [comment]
Try reinstalling both `yo` and `generator-polymer`, this is generally just an installation issue.

```
npm i -g yo generator-polymer
```

**Comment by salah-saleh** [comment]
I did but i still get the same problem.

**Comment by salah-saleh** [comment]
I think I got a lead here. Maybe because my earlier node and npm were installed by brew, but now i use nvm. 
if I type which yo I get: /usr/local/bin/yo 
if I used yo in /Users/sam/.nvm/versions/node/v4.2.2/bin/yo I get no problems. 
any idea how can i fix that?

**Comment by salah-saleh** [comment]
Ok had to delete all the other node, npm versions. Used this Stackoverflow answer:
http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x
