### ISSUE TITLE
Number type argument leads to Error

### ISSUE THREAD

**Issue by zhanziyang** [yeoman/yeoman#1606]
when I run:
yo zyo 5

I get:

    G:\generator-zyo\node_modules\nopt\lib\nopt.js:240
    if (arg.match(/^-{2,}$/)) {
            ^
    TypeError: arg.match is not a function
    at parse (G:\generator-zyo\node_modules\nopt\lib\nopt.js:240:13)
    at nopt (G:\generator-zyo\node_modules\nopt\lib\nopt.js:40:3)
    at Base.parseOptions (G:\generator-zyo\node_modules\yeoman-generator\lib\base.js:344:10)
    at option (G:\generator-zyo\node_modules\yeoman-generator\lib\base.js:274:8)
    at Base (G:\generator-zyo\node_modules\yeoman-generator\lib\base.js:84:8)
    at new module.exports.generators.Base.extend.constructor (G:\generator-zyo\generators\app\index.js:5:21)
    at Environment.instantiate (C:\Users\zhanz\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:328:10)
    at Environment.create (C:\Users\zhanz\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:305:15)
    at Environment.run (C:\Users\zhanz\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:364:24)
    at C:\Users\zhanz\AppData\Roaming\npm\node_modules\yo\lib\cli.js:131:11

**Comment by kevva** [comment]
https://github.com/npm/nopt/issues/42

**Comment by zhanziyang** [comment]
@kevva Thanks!
