### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by drandreaskrueger** [yeoman/yeoman#1607]
Fresh machine, then:

```
apt-get update && apt-get -y upgrade
apt-get -y install sudo build-essential nodejs npm nodejs-legacy
npm install --global yo generator-webapp gulp
```

As seemingly yeoman cannot be run as root:
```
adduser dev
ssh dev@localhost
```

then following the manual

```
mkdir my-webapp
cd my-webapp
yo webapp
gulp serve

```
results in:

```
[17:25:12] Failed to load external module babel-register
[17:25:12] Requiring external module babel-core/register
[17:25:18] Using gulpfile ~/my-webapp/gulpfile.babel.js
[17:25:18] Starting 'styles'...
[17:25:18] Starting 'scripts'...
[17:25:18] Starting 'fonts'...
[17:25:18] Finished 'fonts' after 51 ms

/home/dev/my-webapp/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:157
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
    at LazyResult.async (/home/dev/my-webapp/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/dev/my-webapp/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:79:21)
    at DestroyableTransform._transform (/home/dev/my-webapp/node_modules/gulp-autoprefixer/index.js:24:6)
    at DestroyableTransform.Transform._read (/home/dev/my-webapp/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/dev/my-webapp/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/dev/my-webapp/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/home/dev/my-webapp/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/home/dev/my-webapp/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at DestroyableTransform.ondata (/home/dev/my-webapp/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at DestroyableTransform.emit (events.js:95:17)
```

This might help:

```
node --version && npm --version && gulp --version
v0.10.29
1.4.21
[17:32:49] CLI version 3.9.1
[17:32:49] Local version 3.9.1

```

Is yeoman incompatible with node v0.10 ?

**Comment by SBoudrias** [comment]
The generator you used rely on a build tool that doesn't support Node 0.10.

Yeoman, the tool itself, does support 0.10. But there's no guarantee the generators will.

**Comment by drandreaskrueger** [comment]
Thx.

uninstalled old one

    npm uninstall --global yo generator-webapp gulp
    apt-get remove -y nodejs npm nodejs-legacy

then to get 4.4 on debian

```
apt-get install -y curl
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs npm
npm install --global yo generator-webapp gulp
node --version && npm --version && gulp --version

v4.4.3
2.15.1
[08:15:23] CLI version 3.9.1
[08:15:23] Local version 3.9.1
```

now it works. 

```
...
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:9000
    External: http://...:9000
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://...:3001
 ---------------------------------------
[BS] Serving files from: .tmp
[BS] Serving files from: app

```

Thanks a lot.

I suggest you put a hint into your getting started, about minimum versions.

Thanks for the quick help!
