### ISSUE TITLE
when i use [gulp serve]

### ISSUE THREAD

**Issue by strongant** [yeoman/yeoman#1610]
Warning: a promise was created in a handler but was not returned from it
    at MongoStore.touch (/home/devbwh/study/nodejs/mean/yo/node_modules/connect-mongo/src/index.js:273:18)
    at ServerResponse.end (/home/devbwh/study/nodejs/mean/yo/node_modules/express-session/index.js:301:15)
    at ServerResponse.send (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/response.js:204:10)
    at ServerResponse.json (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/response.js:249:15)
    at thing.controller.js:19:30
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at index (thing.controller.js:65:6)
    at Layer.handle [as handle_request] (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/layer.js:95:5)
    at /home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:330:12)
    at next (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:176:3)
    at router (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:312:13)
    at /home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:330:12)
    at next (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request] (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:312:13)
    at /home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:330:12)
    at next (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:271:10)
    at logger (/home/devbwh/study/nodejs/mean/yo/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:312:13)
    at /home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/devbwh/study/nodejs/mean/yo/node_modules/express/lib/router/index.js:330:12)

**Comment by SBoudrias** [comment]
Open issues on the generator you're using or ask a question on StackOverflow. Yeoman bug tracker is not the right place to post this.
