### ISSUE TITLE
Cannot find module './src/init'

### ISSUE THREAD

**Issue by onuar** [yeoman/yeoman#1637]
I'm trying to create [aspnet project](https://github.com/omnisharp/generator-aspnet#readme) via yo command. I followed this instructions to install yo: http://yeoman.io/learning/

And yo doctor said everything is allright.

yo --version: 1.8.5
npm --version: 3.10.9
node --version: 6.8.0
bower --version: 1.7.9
sw_vers -productVersion: MacOS 10.11.6

-------------
$ yo aspnet
module.js:457
    throw err;
    ^

Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-aspnet/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by SBoudrias** [comment]
Please report bugs running a generator on the specific generator repository.

The Yeoman team works on the core system and is not maintaining the ~5000 publicly available generators.

**Comment by eddiemonge** [comment]
This is a bug in gulp-sourcemaps and has already been reported
