### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/root/.config/configstore

### ISSUE THREAD

**Issue by priyabratta1991** [yeoman/yeoman#1664]
Always getting the EACCES: permission denied while running yeoman in sudo command. 

[root@localhost node_modules]# sudo yo keystone
/usr/lib/node_modules/yo/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/root/.config/configstore'
    at Object.fs.mkdirSync (fs.js:894:18)
    at Function.sync (/usr/lib/node_modules/yo/node_modules/mkdirp/index.js:71:13)
    at Configstore.get (/usr/lib/node_modules/yo/node_modules/configstore/index.js:38:13)
    at Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:172:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

I am running Node v7.7.3 on Fedora 25

**Comment by SBoudrias** [comment]
Your issue is running in sudo mode. It creates unnecessary permission complications.

Try running without sudo. Or you can google `chmod`.
