### ISSUE TITLE
Issue when launching generator

### ISSUE THREAD

**Issue by baarte** [yeoman/yeoman#1665]
Hi,

I get this error when I try to launch a generator with yo:

```
Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo bannertime


     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

/home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/generator-bannertime/generators/app/index.js:12
  constructor(...args) {
              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.defineProperty.get [as bannertime:app] (/home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/home/ubuntu/.nvm/versions/node/v4.7.3/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:261:21)
```

**Comment by sindresorhus** [comment]
The generator you're using uses JavaScript syntax not available in the Node.js version you're using.
