### ISSUE TITLE
Angular2 universal and bootstrap drop down

### ISSUE THREAD

**Issue by shijilesh** [yeoman/yeoman#1667]
import { BsDropdownModule } from 'ngx-bootstrap/dropdown';

@NgModule({
imports: [BsDropdownModule.forRoot(),...]
})

is not working for me, throws the following error . I created asp core angular application via Yeomen aspcorespa generator 

Exception: Call to Node module failed with error: Error: DI Error
at NoProviderError.Error (native)
at NoProviderError.ZoneAwareError (E:\Project\myapp\ClientApp\dist\vendor.js:74873:33)
at NoProviderError.BaseError [as constructor] (E:\Project\myapp\ClientApp\dist\vendor.js:1312:20)
at NoProviderError.AbstractProviderError [as constructor] (E:\Project\myapp\ClientApp\dist\vendor.js:1438:20)
at new NoProviderError (E:\Project\myapp\ClientApp\dist\vendor.js:1478:20)
at ReflectiveInjector_.throwOrNull (E:\Project\myapp\ClientApp\dist\vendor.js:3010:23)
at ReflectiveInjector.getByKeyDefault (E:\Project\myapp\ClientApp\dist\vendor.js:3049:29)
at ReflectiveInjector.getByKey (E:\Project\myapp\ClientApp\dist\vendor.js:2981:29)
at ReflectiveInjector.get (E:\Project\myapp\ClientApp\dist\vendor.js:2850:25)
at NgModuleInjector.get (E:\Project\myapp\ClientApp\dist\vendor.js:8564:56)
at AppView.injectorGet (E:\Project\myapp\ClientApp\dist\vendor.js:12008:49)
at AppView.View_AppComponentx0.createInternal (/AppModule/AppComponentx/component.ngfactory.js:50:156)
at AppView.create (E:\Project\myapp\ClientApp\dist\vendor.js:11951:25)
at AppView.View_AppComponentx_Host0.createInternal (/AppModule/AppComponentx/host.ngfactory.js:15:19)
at AppView.createHostView (E:\Project\myapp\ClientApp\dist\vendor.js:11964:25)

**Comment by SBoudrias** [comment]
Please open an issue on the repository of the generator you used (`generator-aspcorespa`?).

With over 5000 generators, you can understand the Yeoman team doesn't maintains them all. Rather we maintains the tools like yo and the core framework to allow the community to create generators.
