### ISSUE TITLE
ParseError is happening when doing a search

### ISSUE THREAD

**Issue by vitalkanev** [yeoman/yeoman#1675]
```zsh
? 'Allo [object Object]! What would you like to do? Install a generator
? Search npm for generators: awesome list

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

ParseError
    at /usr/lib/node_modules/yo/node_modules/npm-keyword/node_modules/got/index.js:120:14
    at BufferStream.<anonymous> (/usr/lib/node_modules/yo/node_modules/read-all-stream/index.js:64:3)
    at emitNone (events.js:110:20)
    at BufferStream.emit (events.js:207:7)
    at finishMaybe (/usr/lib/node_modules/yo/node_modules/readable-stream/lib/_stream_writable.js:607:14)
    at afterWrite (/usr/lib/node_modules/yo/node_modules/readable-stream/lib/_stream_writable.js:470:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:20)
    at process._tickCallback (internal/process/next_tick.js:180:9)

% yo --version
2.0.0 # from NPM

% uname -a
Linux {COMPUTER-NAME} 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

% node --version && npm --version
v8.5.0
5.3.0
```

**Comment by vitalkanev** [comment]
Oops. It's CLI issue - see yeoman/yo#540
