### ISSUE TITLE
Call twice or more times subgenerator

### ISSUE THREAD

**Issue by AlekseyLeshko** [yeoman/yeoman#1681]
Hello! Firstly, thank you for yeoman!

My subgenerator create some files base on files in  templates folder.
```
this.fs.copyTpl(...);
```

I try to call subgenerator in may main generator.
If I call once
```
this.composeWith(require.resolve('../generatorX'), {
  arguments: ['xxx'],
  params: 'test-params',
});
```
All right, not errors. I have all files from subgenerator templates folder.

And if I call subgenerator twice or more
```
this.composeWith(require.resolve('../generatorX'), {
  arguments: ['xxx'],
  params: 'test-params',
});
this.composeWith(require.resolve('../generatorX'), {
  arguments: ['yyy'],
  params: 'test-params',
});
```
I have some error
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /xxx/generators/xxx/templates/**
    at EditionInterface.exports._copySingle (/xxx/node_modules/mem-fs-editor/lib/actions/copy.js:57:3)
    at files.forEach.file (/xxx/node_modules/mem-fs-editor/lib/actions/copy.js:50:10)
    at Array.forEach (<anonymous>)
    at EditionInterface.exports.copy (/xxx/node_modules/mem-fs-editor/lib/actions/copy.js:49:9)
    at EditionInterface.module.exports [as copyTpl] (/xxx/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at module.exports.writing (/xxx/generators/xxx/index.js:29:13)
    at Object.<anonymous> (/xxx/node_modules/yeoman-generator/lib/index.js:399:25)
    at /xxx/node_modules/run-async/index.js:25:25
    at Promise (<anonymous>)
    at /xxx/node_modules/run-async/index.js:24:19
```

Most likely, locking files while reading.
How wrap subgenerator in promise? How wait until the completion of the subgenerator?

Thankyou for answers and help!

**Comment by SBoudrias** [comment]
The file system is synchronous, it shouldn't lock.

Are you sure the template file really exists?

**Comment by AlekseyLeshko** [comment]
I'm using [copyTml](https://github.com/SBoudrias/mem-fs-editor#copytplfrom-to-context-templateoptions--copyoptions) and not [move](https://github.com/SBoudrias/mem-fs-editor#movefrom-to-options).
How right check exists? After once used subgenerator, all files in templates exists.
May be helped, [my subgenerator](https://github.com/my-brilliant-boilerplate/generator-my-ducks/blob/master/generators/reducer/index.js)

**Comment by AlekseyLeshko** [comment]
I checked files
```javascript
this.fs.exists(path)
```
All files is exists, it's ok.

I try copy one file
```javascript
this.fs.copyTpl( this.templatePath('index.js'), this.destinationPath(path + '/index.js'), tpl);
```
and it's work!

Problem in this.templatePath('**')
```javascript
this.fs.copyTpl(this.templatePath('**'), this.destinationPath(path), tpl);
```

**Comment by SBoudrias** [comment]
I wonder if someone the `template/` folder content change? Maybe a file there gets deleted and then maybe there's a bug where mem-fs-editor tries to copy a deleted file?

**Comment by AlekseyLeshko** [comment]
Files in `templates/` folder not change.
I don't sure, but `fs.exists` say all files is exists. I check file exists before `fs.copyTpl`.

I'm trying some other decision. Code of subgenerator
```javascript
const path = '...';
const files = ['actions', 'index', 'index.test', 'constants', 'selectors'];
const tpl = {
  name: 'xxx'
};

files.map(file => {
  this.fs.copyTpl(
    this.templatePath(`${file}.js`),
    this.destinationPath(`${path}/${file}.js`),
    tpl
  );
});
```
and it's working with once or more calling.

I think the bug/problem in mem-fs-editor. I can create new test repo with implement this case with test.

**Comment by codfish** [comment]
@SBoudrias I'm seeing this as well. I've got two subgenerators, i.e. `api` and `ui`, and both are trying to compose with another subgenerator, i.e. `linting` (smaller generator with a few files that both api and ui should have).

I'm not doing anything special here, just running `copyTpl` (i tried copy to). I'm getting the same error:

`AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/odonnch/Sites/generator-codfish/generators/linting/templates/.*`

in api and ui:

```js
default() {
  this.composeWith(require.resolve('../linting'), { dest: this.options.dest });
}
```

in linting (all files are hidden, hence the `.*` glob):

```js
writing() {
  this.fs.copy(this.templatePath('.*'), this.destinationPath(this.options.dest));
}
```

works on the first one but for some reason the second time around those files aren't found anymore. As if `copy` ran `move` instead

**Comment by codfish** [comment]
```js
this.fs.copy(this.templatePath('.gitignore'), this.destinationPath(this.options.dest, '.gitignore'));
this.fs.copy(this.templatePath('.gitignore'), this.destinationPath(this.options.dest, '.gitignore'));
```

copying a single file twice works, but when i console log the files array that `mem-fs-editor` builds, i get the following:

```
[ '/Users/odonnch/Sites/generator-codfish/generators/api/templates/.gitignore' ]
[ '/Users/odonnch/Sites/generator-codfish/generators/api/templates/.gitignore',
  '/Users/odonnch/Sites/generator-codfish/generators/api/templates/.gitignore' ]
   create foo/.gitignore
```

since you're just concatenating the store files and 

might make sense to remove duplicates here on line 31 in `lib/actions/copy.js` https://github.com/SBoudrias/mem-fs-editor/blob/master/lib/actions/copy.js#L31

```js
var files = [...new Set(diskFiles.concat(storeFiles))];
```

but that's just a small optimization, that won't fix the problem. The odd part here is when you have a glob like:

```js
this.fs.copy(this.templatePath('.*'), this.destinationPath(this.options.dest));
this.fs.copy(this.templatePath('.*'), this.destinationPath(this.options.dest));
```

I get the following when i console.log `files` on line 31 in `copy`:

```
[ '/Users/odonnch/Sites/generator-codfish/generators/api/templates/.gitignore' ]
[ '/Users/odonnch/Sites/generator-codfish/generators/api/templates/.gitignore',
  '/Users/odonnch/Sites/generator-codfish/generators/api/templates/.*',
  '/Users/odonnch/Sites/generator-codfish/generators/api/templates/.gitignore' ]
```

```
AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/odonnch/Sites/generator-codfish/generators/api/templates/.*
    at EditionInterface.exports._copySingle (/Users/odonnch/Sites/generator-codfish/node_modules/mem-fs-editor/lib/actions/copy.js:60:3)
    at files.forEach.file (/Users/odonnch/Sites/generator-codfish/node_modules/mem-fs-editor/lib/actions/copy.js:53:10)
    at Array.forEach (<anonymous>)
    at EditionInterface.exports.copy (/Users/odonnch/Sites/generator-codfish/node_modules/mem-fs-editor/lib/actions/copy.js:52:9)
    at EditionInterface.module.exports [as copyTpl] (/Users/odonnch/Sites/generator-codfish/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
    at module.exports.writing (/Users/odonnch/Sites/generator-codfish/generators/api/index.js:49:19)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/odonnch/Sites/generator-codfish/node_modules/yeoman-generator/lib/index.js:406:18)
    at processImmediate (timers.js:632:19)
```


it has something to do with the actual fromGlob being added directly to the store for something reason, but i cant figure it out yet
