### ISSUE TITLE
npm i fails - Not Found: @sindresorhus/is@0.7.0

### ISSUE THREAD

**Issue by Shmee007** [yeoman/yeoman#1689]
npm version 5.6.0
node version 8.9.4
os windows 7

Log file produced by npm

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'yo' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session ed0efc3cbd2ebdf2
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/yo 427ms (from cache)
8 silly pacote tag manifest for yo@latest fetched in 497ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule yo@2.0.1 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/async 64ms (from cache)
15 silly pacote range manifest for async@^2.1.4 fetched in 75ms
16 silly resolveWithNewModule async@2.6.0 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/got 137ms
18 silly pacote range manifest for got@^8.0.3 fetched in 155ms
19 silly resolveWithNewModule got@8.3.0 checking installable status
20 http fetch GET 200 https://registry.npmjs.org/chalk 173ms
21 silly pacote range manifest for chalk@^1.0.0 fetched in 185ms
22 silly resolveWithNewModule chalk@1.1.3 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/cli-list 187ms (from cache)
24 http fetch GET 200 https://registry.npmjs.org/inquirer 179ms
25 http fetch GET 304 https://registry.npmjs.org/configstore 189ms (from cache)
26 http fetch GET 304 https://registry.npmjs.org/fullname 189ms (from cache)
27 http fetch GET 304 https://registry.npmjs.org/cross-spawn 190ms (from cache)
28 http fetch GET 304 https://registry.npmjs.org/figures 192ms (from cache)
29 silly pacote range manifest for inquirer@^3.0.1 fetched in 189ms
30 silly resolveWithNewModule inquirer@3.3.0 checking installable status
31 silly pacote range manifest for cli-list@^0.2.0 fetched in 198ms
32 silly resolveWithNewModule cli-list@0.2.0 checking installable status
33 silly pacote range manifest for configstore@^3.0.0 fetched in 206ms
34 silly resolveWithNewModule configstore@3.1.1 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/humanize-string 202ms (from cache)
36 silly pacote range manifest for fullname@^3.2.0 fetched in 207ms
37 silly resolveWithNewModule fullname@3.3.0 checking installable status
38 silly pacote range manifest for cross-spawn@^5.0.1 fetched in 213ms
39 silly resolveWithNewModule cross-spawn@5.1.0 checking installable status
40 silly pacote range manifest for figures@^2.0.0 fetched in 217ms
41 silly resolveWithNewModule figures@2.0.0 checking installable status
42 silly pacote range manifest for humanize-string@^1.0.0 fetched in 219ms
43 silly resolveWithNewModule humanize-string@1.0.1 checking installable status
44 http fetch GET 200 https://registry.npmjs.org/lodash 85ms
45 silly pacote range manifest for lodash@^4.17.4 fetched in 103ms
46 silly resolveWithNewModule lodash@4.17.5 checking installable status
47 http fetch GET 200 https://registry.npmjs.org/opn 85ms
48 silly pacote range manifest for opn@^4.0.2 fetched in 91ms
49 silly resolveWithNewModule opn@4.0.2 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/meow 110ms (from cache)
51 http fetch GET 304 https://registry.npmjs.org/npm-keyword 100ms (from cache)
52 http fetch GET 304 https://registry.npmjs.org/package-json 100ms (from cache)
53 http fetch GET 304 https://registry.npmjs.org/read-pkg-up 93ms (from cache)
54 http fetch GET 304 https://registry.npmjs.org/root-check 89ms (from cache)
55 http fetch GET 304 https://registry.npmjs.org/parse-help 98ms (from cache)
56 silly pacote range manifest for meow@^3.0.0 fetched in 124ms
57 silly resolveWithNewModule meow@3.7.0 checking installable status
58 silly pacote range manifest for npm-keyword@^5.0.0 fetched in 116ms
59 silly resolveWithNewModule npm-keyword@5.0.0 checking installable status
60 http fetch GET 304 https://registry.npmjs.org/sort-on 88ms (from cache)
61 silly pacote range manifest for package-json@^4.0.1 fetched in 113ms
62 silly resolveWithNewModule package-json@4.0.1 checking installable status
63 silly pacote range manifest for read-pkg-up@^2.0.0 fetched in 108ms
64 silly resolveWithNewModule read-pkg-up@2.0.0 checking installable status
65 silly pacote range manifest for parse-help@^0.1.1 fetched in 114ms
66 silly resolveWithNewModule parse-help@0.1.1 checking installable status
67 silly pacote range manifest for root-check@^1.0.0 fetched in 107ms
68 silly resolveWithNewModule root-check@1.0.0 checking installable status
69 silly pacote range manifest for sort-on@^2.0.0 fetched in 106ms
70 silly resolveWithNewModule sort-on@2.0.0 checking installable status
71 http fetch GET 304 https://registry.npmjs.org/string-length 114ms (from cache)
72 silly pacote range manifest for string-length@^1.0.0 fetched in 123ms
73 silly resolveWithNewModule string-length@1.0.1 checking installable status
74 http fetch GET 200 https://registry.npmjs.org/update-notifier 79ms
75 http fetch GET 304 https://registry.npmjs.org/tabtab 109ms (from cache)
76 silly pacote range manifest for update-notifier@^2.1.0 fetched in 91ms
77 silly resolveWithNewModule update-notifier@2.3.0 checking installable status
78 silly pacote range manifest for tabtab@^1.3.2 fetched in 124ms
79 silly resolveWithNewModule tabtab@1.3.2 checking installable status
80 http fetch GET 304 https://registry.npmjs.org/titleize 107ms (from cache)
81 http fetch GET 304 https://registry.npmjs.org/insight 348ms (from cache)
82 http fetch GET 304 https://registry.npmjs.org/user-home 101ms (from cache)
83 http fetch GET 304 https://registry.npmjs.org/yeoman-character 97ms (from cache)
84 http fetch GET 304 https://registry.npmjs.org/yeoman-doctor 96ms (from cache)
85 http fetch GET 304 https://registry.npmjs.org/yeoman-environment 98ms (from cache)
86 silly pacote range manifest for titleize@^1.0.0 fetched in 116ms
87 silly resolveWithNewModule titleize@1.0.0 checking installable status
88 http fetch GET 304 https://registry.npmjs.org/yosay 94ms (from cache)
89 silly pacote range manifest for insight@^0.8.4 fetched in 356ms
90 silly resolveWithNewModule insight@0.8.4 checking installable status
91 silly pacote range manifest for yeoman-character@^1.0.0 fetched in 109ms
92 silly resolveWithNewModule yeoman-character@1.1.0 checking installable status
93 silly pacote range manifest for user-home@^2.0.0 fetched in 114ms
94 silly resolveWithNewModule user-home@2.0.0 checking installable status
95 silly pacote range manifest for yeoman-doctor@^2.0.0 fetched in 114ms
96 silly resolveWithNewModule yeoman-doctor@2.1.0 checking installable status
97 silly pacote range manifest for yeoman-environment@^2.0.0 fetched in 116ms
98 silly resolveWithNewModule yeoman-environment@2.0.5 checking installable status
99 silly pacote range manifest for yosay@^2.0.0 fetched in 111ms
100 silly resolveWithNewModule yosay@2.0.1 checking installable status
101 http fetch GET 304 https://registry.npmjs.org/ansi-styles 45ms (from cache)
102 http fetch GET 304 https://registry.npmjs.org/has-ansi 45ms (from cache)
103 http fetch GET 304 https://registry.npmjs.org/escape-string-regexp 47ms (from cache)
104 http fetch GET 304 https://registry.npmjs.org/strip-ansi 48ms (from cache)
105 silly pacote range manifest for ansi-styles@^2.2.1 fetched in 52ms
106 silly resolveWithNewModule ansi-styles@2.2.1 checking installable status
107 silly pacote range manifest for has-ansi@^2.0.0 fetched in 57ms
108 silly resolveWithNewModule has-ansi@2.0.0 checking installable status
109 silly pacote range manifest for escape-string-regexp@^1.0.2 fetched in 61ms
110 silly resolveWithNewModule escape-string-regexp@1.0.5 checking installable status
111 http fetch GET 304 https://registry.npmjs.org/supports-color 65ms (from cache)
112 silly pacote range manifest for strip-ansi@^3.0.0 fetched in 69ms
113 silly resolveWithNewModule strip-ansi@3.0.1 checking installable status
114 silly pacote range manifest for supports-color@^2.0.0 fetched in 71ms
115 silly resolveWithNewModule supports-color@2.0.0 checking installable status
116 http fetch GET 304 https://registry.npmjs.org/ansi-regex 27ms (from cache)
117 silly pacote range manifest for ansi-regex@^2.0.0 fetched in 30ms
118 silly resolveWithNewModule ansi-regex@2.1.1 checking installable status
119 http fetch GET 200 https://registry.npmjs.org/dot-prop 60ms
120 silly pacote range manifest for dot-prop@^4.1.0 fetched in 69ms
121 silly resolveWithNewModule dot-prop@4.2.0 checking installable status
122 http fetch GET 304 https://registry.npmjs.org/unique-string 69ms (from cache)
123 http fetch GET 304 https://registry.npmjs.org/graceful-fs 73ms (from cache)
124 http fetch GET 304 https://registry.npmjs.org/xdg-basedir 76ms (from cache)
125 silly pacote range manifest for unique-string@^1.0.0 fetched in 82ms
126 silly resolveWithNewModule unique-string@1.0.0 checking installable status
127 silly pacote range manifest for graceful-fs@^4.1.2 fetched in 84ms
128 silly resolveWithNewModule graceful-fs@4.1.11 checking installable status
129 http fetch GET 304 https://registry.npmjs.org/write-file-atomic 99ms (from cache)
130 silly pacote range manifest for xdg-basedir@^3.0.0 fetched in 100ms
131 silly resolveWithNewModule xdg-basedir@3.0.0 checking installable status
132 http fetch GET 304 https://registry.npmjs.org/make-dir 104ms (from cache)
133 silly pacote range manifest for write-file-atomic@^2.0.0 fetched in 107ms
134 silly resolveWithNewModule write-file-atomic@2.3.0 checking installable status
135 silly pacote range manifest for make-dir@^1.0.0 fetched in 110ms
136 silly resolveWithNewModule make-dir@1.2.0 checking installable status
137 http fetch GET 304 https://registry.npmjs.org/is-obj 34ms (from cache)
138 silly pacote range manifest for is-obj@^1.0.0 fetched in 37ms
139 silly resolveWithNewModule is-obj@1.0.1 checking installable status
140 http fetch GET 304 https://registry.npmjs.org/pify 29ms (from cache)
141 silly pacote range manifest for pify@^3.0.0 fetched in 34ms
142 silly resolveWithNewModule pify@3.0.0 checking installable status
143 http fetch GET 304 https://registry.npmjs.org/crypto-random-string 20ms (from cache)
144 silly pacote range manifest for crypto-random-string@^1.0.0 fetched in 22ms
145 silly resolveWithNewModule crypto-random-string@1.0.0 checking installable status
146 http fetch GET 304 https://registry.npmjs.org/imurmurhash 31ms (from cache)
147 http fetch GET 304 https://registry.npmjs.org/signal-exit 33ms (from cache)
148 silly pacote range manifest for imurmurhash@^0.1.4 fetched in 35ms
149 silly resolveWithNewModule imurmurhash@0.1.4 checking installable status
150 silly pacote range manifest for signal-exit@^3.0.2 fetched in 37ms
151 silly resolveWithNewModule signal-exit@3.0.2 checking installable status
152 http fetch GET 304 https://registry.npmjs.org/lru-cache 28ms (from cache)
153 silly pacote range manifest for lru-cache@^4.0.1 fetched in 35ms
154 silly resolveWithNewModule lru-cache@4.1.2 checking installable status
155 http fetch GET 304 https://registry.npmjs.org/shebang-command 38ms (from cache)
156 http fetch GET 304 https://registry.npmjs.org/which 39ms (from cache)
157 silly pacote range manifest for which@^1.2.9 fetched in 43ms
158 silly resolveWithNewModule which@1.3.0 checking installable status
159 silly pacote range manifest for shebang-command@^1.2.0 fetched in 44ms
160 silly resolveWithNewModule shebang-command@1.2.0 checking installable status
161 http fetch GET 304 https://registry.npmjs.org/yallist 20ms (from cache)
162 http fetch GET 304 https://registry.npmjs.org/pseudomap 21ms (from cache)
163 silly pacote range manifest for pseudomap@^1.0.2 fetched in 27ms
164 silly resolveWithNewModule pseudomap@1.0.2 checking installable status
165 silly pacote range manifest for yallist@^2.1.2 fetched in 28ms
166 silly resolveWithNewModule yallist@2.1.2 checking installable status
167 http fetch GET 304 https://registry.npmjs.org/shebang-regex 26ms (from cache)
168 silly pacote range manifest for shebang-regex@^1.0.0 fetched in 28ms
169 silly resolveWithNewModule shebang-regex@1.0.0 checking installable status
170 http fetch GET 304 https://registry.npmjs.org/isexe 32ms (from cache)
171 silly pacote range manifest for isexe@^2.0.0 fetched in 54ms
172 silly resolveWithNewModule isexe@2.0.0 checking installable status
173 http fetch GET 304 https://registry.npmjs.org/p-try 109ms (from cache)
174 http fetch GET 304 https://registry.npmjs.org/filter-obj 110ms (from cache)
175 http fetch GET 304 https://registry.npmjs.org/passwd-user 109ms (from cache)
176 http fetch GET 304 https://registry.npmjs.org/mem 112ms (from cache)
177 http fetch GET 304 https://registry.npmjs.org/execa 116ms (from cache)
178 http fetch GET 304 https://registry.npmjs.org/p-any 116ms (from cache)
179 http fetch GET 304 https://registry.npmjs.org/rc 116ms (from cache)
180 silly pacote range manifest for p-try@^1.0.0 fetched in 117ms
181 silly resolveWithNewModule p-try@1.0.0 checking installable status
182 silly pacote range manifest for passwd-user@^2.1.0 fetched in 118ms
183 silly resolveWithNewModule passwd-user@2.1.0 checking installable status
184 silly pacote range manifest for filter-obj@^1.1.0 fetched in 126ms
185 silly resolveWithNewModule filter-obj@1.1.0 checking installable status
186 silly pacote range manifest for p-any@^1.0.0 fetched in 128ms
187 silly resolveWithNewModule p-any@1.1.0 checking installable status
188 silly pacote range manifest for rc@^1.1.6 fetched in 129ms
189 silly resolveWithNewModule rc@1.2.6 checking installable status
190 silly pacote range manifest for execa@^0.6.0 fetched in 132ms
191 silly resolveWithNewModule execa@0.6.3 checking installable status
192 silly pacote range manifest for mem@^1.1.0 fetched in 131ms
193 silly resolveWithNewModule mem@1.1.0 checking installable status
194 http fetch GET 304 https://registry.npmjs.org/is-stream 36ms (from cache)
195 silly pacote range manifest for is-stream@^1.1.0 fetched in 40ms
196 silly resolveWithNewModule is-stream@1.1.0 checking installable status
197 http fetch GET 304 https://registry.npmjs.org/get-stream 41ms (from cache)
198 http fetch GET 304 https://registry.npmjs.org/strip-eof 40ms (from cache)
199 http fetch GET 304 https://registry.npmjs.org/npm-run-path 43ms (from cache)
200 silly pacote range manifest for get-stream@^3.0.0 fetched in 46ms
201 silly resolveWithNewModule get-stream@3.0.0 checking installable status
202 silly pacote range manifest for strip-eof@^1.0.0 fetched in 46ms
203 silly resolveWithNewModule strip-eof@1.0.0 checking installable status
204 silly pacote range manifest for npm-run-path@^2.0.0 fetched in 47ms
205 silly resolveWithNewModule npm-run-path@2.0.2 checking installable status
206 http fetch GET 304 https://registry.npmjs.org/p-finally 48ms (from cache)
207 silly pacote range manifest for p-finally@^1.0.0 fetched in 54ms
208 silly resolveWithNewModule p-finally@1.0.0 checking installable status
209 http fetch GET 304 https://registry.npmjs.org/path-key 18ms (from cache)
210 silly pacote range manifest for path-key@^2.0.0 fetched in 20ms
211 silly resolveWithNewModule path-key@2.0.1 checking installable status
212 http fetch GET 304 https://registry.npmjs.org/mimic-fn 20ms (from cache)
213 silly pacote range manifest for mimic-fn@^1.0.0 fetched in 22ms
214 silly resolveWithNewModule mimic-fn@1.2.0 checking installable status
215 http fetch GET 304 https://registry.npmjs.org/p-some 17ms (from cache)
216 silly pacote range manifest for p-some@^2.0.0 fetched in 19ms
217 silly resolveWithNewModule p-some@2.0.1 checking installable status
218 http fetch GET 304 https://registry.npmjs.org/aggregate-error 21ms (from cache)
219 silly pacote range manifest for aggregate-error@^1.0.0 fetched in 24ms
220 silly resolveWithNewModule aggregate-error@1.0.0 checking installable status
221 http fetch GET 304 https://registry.npmjs.org/indent-string 23ms (from cache)
222 silly pacote range manifest for indent-string@^3.0.0 fetched in 25ms
223 silly resolveWithNewModule indent-string@3.2.0 checking installable status
224 http fetch GET 304 https://registry.npmjs.org/clean-stack 181ms (from cache)
225 silly pacote range manifest for clean-stack@^1.0.0 fetched in 183ms
226 silly resolveWithNewModule clean-stack@1.3.0 checking installable status
227 silly pacote range manifest for execa@^0.4.0 fetched in 3ms
228 silly resolveWithNewModule execa@0.4.0 checking installable status
229 silly pacote range manifest for pify@^2.3.0 fetched in 4ms
230 silly resolveWithNewModule pify@2.3.0 checking installable status
231 silly pacote range manifest for npm-run-path@^1.0.0 fetched in 5ms
232 silly resolveWithNewModule npm-run-path@1.0.0 checking installable status
233 silly pacote range manifest for path-key@^1.0.0 fetched in 8ms
234 silly resolveWithNewModule path-key@1.0.0 checking installable status
235 http fetch GET 304 https://registry.npmjs.org/object-assign 33ms (from cache)
236 http fetch GET 200 https://registry.npmjs.org/cross-spawn-async 36ms
237 silly pacote range manifest for object-assign@^4.0.1 fetched in 40ms
238 silly resolveWithNewModule object-assign@4.1.1 checking installable status
239 silly pacote range manifest for cross-spawn-async@^2.1.1 fetched in 44ms
240 silly resolveWithNewModule cross-spawn-async@2.2.5 checking installable status
241 http fetch GET 304 https://registry.npmjs.org/ini 29ms (from cache)
242 http fetch GET 304 https://registry.npmjs.org/deep-extend 30ms (from cache)
243 http fetch GET 200 https://registry.npmjs.org/minimist 31ms
244 http fetch GET 304 https://registry.npmjs.org/strip-json-comments 31ms (from cache)
245 silly pacote range manifest for deep-extend@~0.4.0 fetched in 34ms
246 silly resolveWithNewModule deep-extend@0.4.2 checking installable status
247 silly pacote range manifest for ini@~1.3.0 fetched in 34ms
248 silly resolveWithNewModule ini@1.3.5 checking installable status
249 silly pacote range manifest for minimist@^1.2.0 fetched in 35ms
250 silly resolveWithNewModule minimist@1.2.0 checking installable status
251 silly pacote range manifest for strip-json-comments@~2.0.1 fetched in 34ms
252 silly resolveWithNewModule strip-json-comments@2.0.1 checking installable status
253 http fetch GET 304 https://registry.npmjs.org/duplexer3 66ms (from cache)
254 http fetch GET 304 https://registry.npmjs.org/into-stream 66ms (from cache)
255 http fetch GET 304 https://registry.npmjs.org/decompress-response 67ms (from cache)
256 http fetch GET 304 https://registry.npmjs.org/mimic-response 67ms (from cache)
257 http fetch GET 304 https://registry.npmjs.org/isurl 68ms (from cache)
258 http fetch GET 304 https://registry.npmjs.org/lowercase-keys 69ms (from cache)
259 silly pacote range manifest for into-stream@^3.1.0 fetched in 71ms
260 silly resolveWithNewModule into-stream@3.1.0 checking installable status
261 silly pacote range manifest for mimic-response@^1.0.0 fetched in 72ms
262 silly resolveWithNewModule mimic-response@1.0.0 checking installable status
263 silly pacote range manifest for duplexer3@^0.1.4 fetched in 75ms
264 silly resolveWithNewModule duplexer3@0.1.4 checking installable status
265 silly pacote range manifest for decompress-response@^3.3.0 fetched in 77ms
266 silly resolveWithNewModule decompress-response@3.3.0 checking installable status
267 silly pacote range manifest for lowercase-keys@^1.0.0 fetched in 76ms
268 silly resolveWithNewModule lowercase-keys@1.0.0 checking installable status
269 silly pacote range manifest for isurl@^1.0.0-alpha5 fetched in 79ms
270 silly resolveWithNewModule isurl@1.0.0 checking installable status
271 http fetch GET 304 https://registry.npmjs.org/is-retry-allowed 80ms (from cache)
272 silly pacote range manifest for is-retry-allowed@^1.1.0 fetched in 154ms
273 silly resolveWithNewModule is-retry-allowed@1.1.0 checking installable status
274 http fetch GET 304 https://registry.npmjs.org/cacheable-request 181ms (from cache)
275 silly pacote range manifest for cacheable-request@^2.1.1 fetched in 190ms
276 silly resolveWithNewModule cacheable-request@2.1.4 checking installable status
277 http fetch GET 304 https://registry.npmjs.org/safe-buffer 118ms (from cache)
278 http fetch GET 304 https://registry.npmjs.org/p-timeout 121ms (from cache)
279 http fetch GET 304 https://registry.npmjs.org/url-parse-lax 118ms (from cache)
280 http fetch GET 304 https://registry.npmjs.org/p-cancelable 195ms (from cache)
281 silly pacote range manifest for p-timeout@^2.0.1 fetched in 127ms
282 silly resolveWithNewModule p-timeout@2.0.1 checking installable status
283 silly pacote range manifest for safe-buffer@^5.1.1 fetched in 125ms
284 silly resolveWithNewModule safe-buffer@5.1.1 checking installable status
285 http fetch GET 304 https://registry.npmjs.org/url-to-options 122ms (from cache)
286 silly pacote range manifest for url-parse-lax@^3.0.0 fetched in 124ms
287 silly resolveWithNewModule url-parse-lax@3.0.0 checking installable status
288 silly pacote range manifest for p-cancelable@^0.4.0 fetched in 201ms
289 silly resolveWithNewModule p-cancelable@0.4.0 checking installable status
290 http fetch GET 304 https://registry.npmjs.org/timed-out 126ms (from cache)
291 silly pacote range manifest for url-to-options@^1.0.1 fetched in 126ms
292 silly resolveWithNewModule url-to-options@1.0.1 checking installable status
293 silly pacote range manifest for timed-out@^4.0.1 fetched in 129ms
294 silly resolveWithNewModule timed-out@4.0.1 checking installable status
295 http fetch GET 404 https://registry.npmjs.org/@sindresorhus%2fis 674ms
296 silly fetchPackageMetaData error for @sindresorhus/is@^0.7.0 404 Not Found: @sindresorhus/is@^0.7.0
297 verbose stack Error: 404 Not Found: @sindresorhus/is@^0.7.0
297 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
297 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
297 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
297 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
297 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
297 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
297 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
297 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
297 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
297 verbose stack     at runCallback (timers.js:789:20)
297 verbose stack     at tryOnImmediate (timers.js:751:5)
297 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
298 verbose cwd D:\dev
299 verbose Windows_NT 6.1.7601
300 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
301 verbose node v8.9.4
302 verbose npm  v5.6.0
303 error code E404
304 error 404 Not Found: @sindresorhus/is@^0.7.0
305 verbose exit [ 1, true ]
```

**Comment by mischah** [comment]
No Problems over here 🤔 

Do you get a JSON result when openening this page?
https://registry.npmjs.org/@sindresorhus%2fis

**Comment by Shmee007** [comment]
Yes.
Updated the log file, added the sindresorhus/is only one

**Comment by Shmee007** [comment]
Would you like that added to a comment or anything else I can do?

**Comment by mischah** [comment]
Are you able to install the package via:

```
npm install @sindresorhus/is@^0.7.0
```

**Comment by Shmee007** [comment]
@sindresorhus  was not mush help, just refered me to the npm issue tracker and closed the issue.
I assume @sindresorhus believe it's unrelated related to his/her package.

**Comment by mischah** [comment]
> No, raised the issue on their page. Thanks for the help so far!

It really seems to be a npm issue on your machine.

Still wondering why it’s this package that causes the 404 error 🤔 
See also https://github.com/graphcool/chromeless/issues/416

I’d suggest writing a email to <support@npmjs.com>

**Comment by Shmee007** [comment]
Thanks a lot @mischah appreciate your support!

**Comment by vivganes** [comment]
I got the same error when I was using a proxy npm locally (sinopia to be specific) but when I switched to public npm registry, the error is not there anymore.

If you are using sinopia, try using public registry directly.

**Comment by Shmee007** [comment]
Thanks, but tried that, even disconnected from the company network to make sure it was going directly to web repo

**Comment by xwwww** [comment]
I got the same error , and it was solved when I switched to another npm registry.

**Comment by shabalin** [comment]
npm login, fixed that for me

**Comment by Hano1388** [comment]
I believe the issue raises when uninstalling node and installing a new version, then we are some how logged out so, we need to re-login. npm login worked for me

**Comment by guru-katre-mpf** [comment]
If you are using sinopia then this happens.
To install public package first set registry as below and then install npm package
npm set registry https://registry.npmjs.org/

**Comment by StepanDev** [comment]
@mischah 

> No Problems over here 🤔
> 
> Do you get a JSON result when openening this page?
> https://registry.npmjs.org/@sindresorhus%2fis

@mischah i faced the same issue, but when I visit this link I get {"error":"Not found"}. Is it a problem with my network or what?

**Comment by ghost** [comment]
> @mischah
> 
> > No Problems over here 🤔
> > Do you get a JSON result when openening this page?
> > https://registry.npmjs.org/@sindresorhus%2fis
> 
> @mischah i faced the same issue, but when I visit this link I get {"error":"Not found"}. Is it a problem with my network or what?

Same right here

**Comment by jacobleech** [comment]
> > @mischah
> > > No Problems over here 🤔
> > > Do you get a JSON result when openening this page?
> > > https://registry.npmjs.org/@sindresorhus%2fis
> > 
> > 
> > @mischah i faced the same issue, but when I visit this link I get {"error":"Not found"}. Is it a problem with my network or what?
> 
> Same right here

Can confirm, same issue here. Can't setup a project I'm trying to work on.

**Comment by Acika00mk** [comment]
Same issue appears here, 
Is this a npm error ?

**Comment by kbruneel** [comment]
NPM is having some issues, so it could be that: https://status.npmjs.org/

I have the same problem.

**Comment by redixhumayun** [comment]
It seems to be back up now

**Comment by StepanDev** [comment]
Yes, in my case that was npm issue. Now it works.

**Comment by Acika00mk** [comment]
Status update, 
It is fixed 
`Resolved - The incident has been resolved and we see no errors with installing packages anymore.
Aug 6, 12:01 UTC`

**Comment by UlisesGascon** [comment]
NPM was down few hours ago. I will lock the conversation as the original issue was already solved in 2018 :-)
![Captura de pantalla 2020-08-06 a las 14 27 21](https://user-images.githubusercontent.com/5110813/89531845-28cf8400-d7f1-11ea-9cb0-beec57453fb6.png)
