### ISSUE TITLE
Version 2.0.3 has a network timeout issue

### ISSUE THREAD

**Issue by wsrast** [yeoman/yeoman#1694]
I've updated to the 2.0.3 version and it looks like there's a problem with a network timeout. Downgrading back to 2.0.2 works.

A "yo doctor" reveals this:

`Yeoman Doctor                                                                                      
Running sanity checks on your system                                                               
                                                                                                   
√ Global configuration file is valid                                                               
√ NODE_PATH matches the npm root                                                                   
√ Node.js version                                                                                  
√ No .bowerrc file in home directory                                                               
√ No .yo-rc.json file in home directory                                                            
{ RequestError: connect ETIMEDOUT xxx.xx.xx.xx:80                                                  
    at ClientRequest.req.once.err (C:\Users\myuser\AppData\Roaming\nvm\v8.11.3\node_modules\yo\node
_modules\latest-version\node_modules\got\index.js:73:21)                                           
    at Object.onceWrapper (events.js:315:30)                                                       
    at emitOne (events.js:116:13)                                                                  
    at ClientRequest.emit (events.js:211:7)                                                        
    at Socket.socketErrorListener (_http_client.js:387:9)                                          
    at emitOne (events.js:116:13)                                                                  
    at Socket.emit (events.js:211:7)                                                               
    at emitErrorNT (internal/streams/destroy.js:64:8)                                              
    at _combinedTickCallback (internal/process/next_tick.js:138:11)                                
    at process._tickCallback (internal/process/next_tick.js:180:9)                                 
  code: 'ETIMEDOUT',                                                                               
  message: 'connect ETIMEDOUT xxx.xx.xx.xx:80',                                                    
  host: 'registry.npmjs.org',                                                                      
  hostname: 'registry.npmjs.org',                                                                  
  method: 'GET',                                                                                   
  path: '/yo' }                                                                                    
× yo version                                                                                       
{ RequestError: connect ETIMEDOUT xxx.xx.xx.xx:80                                                  
    at ClientRequest.req.once.err (C:\Users\myuser\AppData\Roaming\nvm\v8.11.3\node_modules\yo\node
_modules\latest-version\node_modules\got\index.js:73:21)                                           
    at Object.onceWrapper (events.js:315:30)                                                       
    at emitOne (events.js:116:13)                                                                  
    at ClientRequest.emit (events.js:211:7)                                                        
    at Socket.socketErrorListener (_http_client.js:387:9)                                          
    at emitOne (events.js:116:13)                                                                  
    at Socket.emit (events.js:211:7)                                                               
    at emitErrorNT (internal/streams/destroy.js:64:8)                                              
    at _combinedTickCallback (internal/process/next_tick.js:138:11)                                
    at process._tickCallback (internal/process/next_tick.js:180:9)                                 
  code: 'ETIMEDOUT',                                                                               
  message: 'connect ETIMEDOUT xxx.xx.xx.xx:80',                                                    
  host: 'registry.npmjs.org',                                                                      
  hostname: 'registry.npmjs.org',                                                                  
  method: 'GET',                                                                                   
  path: '/yo' }                                                                                    
× yo version                                                                                       
                                                                                                   
Your yo version is outdated.                                                                       
                                                                                                   
Upgrade to the latest version by running:                                                          
npm install -g yo@latest`                                                                           

Also, the doctor is erroneously reporting that I don't have the most recent version: I have 2.0.3, which I just installed to make sure I was updated.

I downgraded to 2.0.2 with "npm i -g yo@2.0.2" and the problem goes away.

**Comment by SBoudrias** [comment]
Are you behind a proxy by any chance? Or have PROXY environment variables setup?

**Comment by wsrast** [comment]
I am behind a proxy, yes. I've verified that I don't have any of the proxy environment variables set up.

Is there some new reliance in 2.0.3 on specific proxy settings? 2.0.2 is working properly with my existing settings.

**Comment by SBoudrias** [comment]
We included [global-tunnel-ng](https://github.com/np-maintain/global-tunnel) package to help out user using proxies. Maybe you could look at the documentation and let me know if you find what was wrong.

If it's just not stable and keep causing issues to users, we might consider removing this package in the future.

cc @MarcoScabbiolo - any idea what could be wrong here?

**Comment by MarcoScabbiolo** [comment]
@wsrast I'm thinking you have some residual configurations that are pointing to a proxy that is not responding.

Could you run the following and share the output?

```bash
echo $https_proxy
echo $HTTPS_PROXY
echo $http_proxy
echo $HTTP_PROXY
npm config get proxy
npm config get https-proxy
npm config get http-proxy
```

**Comment by wsrast** [comment]
Marco, I'm on a Windows system, so I've modified your commands for my environment. The results are all empty on the environment variables, and the npm commands come back as:
proxy: (corp proxy)
http-proxy: undefined
https-proxy (corp proxy)

**Comment by MarcoScabbiolo** [comment]
`https-proxy` is the one being used, as it takes presedence over `proxy`. Is it an https proxy? Does it work if you remove this setting and keep only `proxy`?

**Comment by wsrast** [comment]
Unfortunately, the removal of the https-proxy setting doesn't fix the issue. **However**, I've tried out using Yarn's global installation and that appears to work fine, with no changes to the proxy settings; no error messages are seen.

Here's the full dump of the NPM error.

```
Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
{ RequestError: connect ETIMEDOUT xxx:443
    at ClientRequest.req.once.err (C:\Users\myuser\AppData\Roaming\npm\node_modules\yo\node_modules\latest-version\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT xxx:443',
  host: 'private-host.pkgs.visualstudio.com',
  hostname: 'private-host.pkgs.visualstudio.com',
  method: 'GET',
  path: '/_packaging/npm-feed/npm/registry/yo' }
× yo version
{ RequestError: connect ETIMEDOUT xxx:443
    at ClientRequest.req.once.err (C:\Users\myuser\AppData\Roaming\npm\node_modules\yo\node_modules\latest-version\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT xxx:443',
  host: 'private-host.pkgs.visualstudio.com',
  hostname: 'private-host.pkgs.visualstudio.com',
  method: 'GET',
  path: '/_packaging/npm-feed/npm/registry/yo' }
× yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest

(node:12416) UnhandledPromiseRejectionWarning: Error: callback() can only be called once.
    at onetime (C:\Users\rastwe\AppData\Roaming\npm\node_modules\yo\node_modules\each-async\node_modules\onetime\index.js:15:11)
    at rule.verify.err (C:\Users\rastwe\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-doctor\lib\index.js:23:7)
    at binVersionCheck.then (C:\Users\rastwe\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-doctor\lib\rules\yo-version.js:21:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:12416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
√ npm version

Found potential issues on your machine :(
+ yo@2.0.4
added 538 packages in 365.868s
```

Again, yo is erroneously reporting that my version isn't up to date.

For comparison, here is the output from the Yarn installer:
```
> yarn global add yo
yarn global v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "yo@2.0.4" with binaries:
      - yo
      - yo-complete
Done in 247.93s.```

**Comment by SBoudrias** [comment]
@wsrast about the version warning reported by yo doctor, it's most likely a path issue. This seem to be frequent recently, I wonder if yarn or npm changed their installation folder structure recently - so maybe the PATH variable still point at an old location with an old version.

**Comment by wsrast** [comment]
@SBoudrias re: the old version. I've tried uninstalling node and all associated libraries and starting again with a clean system. I'd be surprised if there's still an old version being found somewhere after something that drastic.

**Comment by SBoudrias** [comment]
@wsrast uninstalling node won't actually clear npm global installation folders. This would most likely require manual operation.

**Comment by Dereeg** [comment]
I am having the exactly same problem under a corporate proxy. I have all my proxies working with npm and yarn, so trying to figure it out what is the issue with yeoman.

**Comment by haakon-io** [comment]
Did someone figure out how to fix this? I'm seeing the exact same issue.

**Comment by charsj** [comment]
I am also running into this issue. Has anyone found a solution yet?

**Comment by jedmao** [comment]
Same issue, one year after OP.

**Comment by Carracer66** [comment]
as per the global-agent README.md, you must set GLOBAL_AGENT_HTTP_PROXY=http://<server>:<port>

Issue resolved!  Why was this buried in the README file!?!

**Comment by asmallkite** [comment]
@Carracer66 Thank you.Solved my problem.

**Comment by UlisesGascon** [comment]
Thanks @Carracer66 for share this solution! :-)

@wsrast can you try it? I close this issue, but If this is still an issue please let us know

**Comment by vardaro** [comment]
This worked on my machine as well. Thanks :)
