### ISSUE TITLE
YO install issue ( Error: Cannot find module 'minimist' )

### ISSUE THREAD

**Issue by insetavijit** [yeoman/yeoman#1698]
# i am unable to install yo with

- node stable version ( 8.11.3 
- npm @5.5.1
- node js current version ( 10.x.x)
- npm @6.1.1

> ## using windows 10 ( pro N )
please let me know what is the problem ?

full console out put is listed bellow
```

PS C:\Users\avijit> npm i -g yo
C:\Users\avijit\AppData\Roaming\npm\yo-complete -> C:\Users\avijit\AppData\Roaming\npm\node_modules\yo\lib\completion\index.js
C:\Users\avijit\AppData\Roaming\npm\yo -> C:\Users\avijit\AppData\Roaming\npm\node_modules\yo\lib\cli.js

> spawn-sync@1.0.15 postinstall C:\Users\avijit\AppData\Roaming\npm\node_modules\yo\node_modules\spawn-sync
> node postinstall


> yo@2.0.5 postinstall C:\Users\avijit\AppData\Roaming\npm\node_modules\yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
module.js:549
    throw err;
    ^

Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\Users\avijit\AppData\Roaming\npm\node_modules\yo\node_modules\rc\index.js:14:12)
    at module.exports (C:\Users\avijit\AppData\Roaming\npm\node_modules\yo\node_modules\registry-url\index.js:3:24)
    at module.exports (C:\Users\avijit\AppData\Roaming\npm\node_modules\yo\node_modules\latest-version\node_modules\package-json\index.js:10:17)
    at module.exports.name (C:\Users\avijit\AppData\Roaming\npm\node_modules\yo\node_modules\latest-version\index.js:4:26)
    at Object.exports.verify.cb [as verify] (C:\Users\avijit\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-doctor\lib\rules\yo-version.js:16:3)
    at Immediate.eachAsync [as _onImmediate] (C:\Users\avijit\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-doctor\lib\index.js:15:10)
npm WARN Error: EPERM: operation not permitted, scandir 'C:\Users\avijit\AppData\Roaming\npm\node_modules\yo\node_modules\to-object-path\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Users\avijit\AppData\Roaming\npm\node_modules\yo\node_modules\to-object-path\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\avijit\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\to-object-path\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\Users\\avijit\\AppData\\Roaming\\npm\\node_modules\\yo\\node_modules\\to-object-path\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yo@2.0.5 postinstall: `yodoctor`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yo@2.0.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\avijit\AppData\Roaming\npm-cache\_logs\2018-07-25T14_51_41_044Z-debug.log
PS C:\Users\avijit> npm -v
5.5.1
```

**Comment by JoshuaKGoldberg** [comment]
No longer reproduces for me. I'm guessing this was a transient issue with the network or package registry.

If someone does get this, please do post back - we can take a look.

Cheers! 🎩
