### ISSUE TITLE
Yeoman behind Zscaler proxy

### ISSUE THREAD

**Issue by michalejoye** [yeoman/yeoman#1699]
I am unable to run any yo command(even yo doctor) without getting this error:

```
C:\Users\mjoye\AppData\Roaming\npm\node_modules\yo\node_modules\global-tunnel-ng\index.js:226
    throw e;
    ^

Error: upstream proxy port is required
    at globalTunnel.initialize (C:\Users\mjoye\AppData\Roaming\npm\node_modules\yo\node_modules\global-tunnel-ng\index.js:189:13)
    at Object.<anonymous> (C:\Users\mjoye\AppData\Roaming\npm\node_modules\yo\lib\cli.js:20:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

I am able to run `yodoctor` and I get this error:

```
Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version
{ RequestError: read ECONNRESET
    at ClientRequest.req.once.err (C:\Users\mjoye\AppData\Roaming\npm\node_modules\yo\node_modules\latest-version\node_modules\got\index.js:73:21)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ECONNRESET',
  message: 'read ECONNRESET',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo' }
× yo version
{ RequestError: read ECONNRESET
    at ClientRequest.req.once.err (C:\Users\mjoye\AppData\Roaming\npm\node_modules\yo\node_modules\latest-version\node_modules\got\index.js:73:21)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ECONNRESET',
  message: 'read ECONNRESET',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo' }

Found potential issues on your machine :(
× yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest
```

**Comment by tremblaysimon** [comment]
Seems to be related to https://github.com/yeoman/doctor/issues/40.
