### ISSUE TITLE
Yo install issue:  upstream proxy port is required

### ISSUE THREAD

**Issue by xusine** [yeoman/yeoman#1710]
Hi, and I'm using npm to install yo:
```shell
npm install -g yo
```
And I get an error message like this:

```
Yeoman Doctor
Running sanity checks on your system

/home/xusine/.npm-packages/lib/node_modules/yo/node_modules/global-tunnel-ng/index.js:231
    throw e;
    ^

Error: upstream proxy port is required
    at Object.globalTunnel.initialize (/home/xusine/.npm-packages/lib/node_modules/yo/node_modules/global-tunnel-ng/index.js:192:13)
    at Object.<anonymous> (/home/xusine/.npm-packages/lib/node_modules/yo/node_modules/yeoman-doctor/lib/cli.js:6:29)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yo@2.0.6 postinstall: `yodoctor`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yo@2.0.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

My node version is 10.15.3 and npm version is 6.4.1. Thanks!

**Comment by UlisesGascon** [comment]
@Xusine1131  which os system do you have?

**Comment by Xusine1131** [comment]
A Linux distribution called Deepin. And its version is 15.10.1. 
@UlisesGascon

**Comment by eddiemonge** [comment]
That's a new error to me.

**Comment by Oleg4370** [comment]
Any updates about this error?
I have the same issue on my macOS Catalina and node v12.13.0

**Comment by abelmark** [comment]
I'm receiving the same error.  node v8.9.4

**Comment by JoshuaKGoldberg** [comment]
I believe this is external to yeoman/yeoman-doctor/yo. Example SO answer for Windows users: https://stackoverflow.com/questions/53558172/yeoman-generator-error-upstream-proxy-port-is-required

> Is it possible that you're in a work environment behind a proxy? If you're not sure you can check if there's a proxy configured in IE settings or by running the following command in your command line
>
> ```shell
> netsh winhttp show proxy
> ```
>
> If that's the case, you'll need to run the following command replacing the proxy url
>
> ```shell
> npm config set proxy <proxy_url>
> ```

ACK that folks here are posting about not-Windows OSes. The `npm config set proxy` command is relevant there too. See https://docs.npmjs.com/cli/v10/using-npm/config#https-proxy. 

I might be wrong in closing this out, but since it's been almost 5 years since someone posted my hunch is it's not an issue in Yeoman itself. Yeoman packages aren't doing anything fancy with the network themselves. If you're still getting this, please do post back with more information. Cheers! 🎩
