### ISSUE TITLE
Broken fs.copy

### ISSUE THREAD

**Issue by dangreen** [yeoman/yeoman#1712]
```
Error: ENOTDIR: not a directory, stat '/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/weather/.trigen-template/TrigenSoftware-weather-711cd3e/README.md/**'
    at Object.statSync (fs.js:871:3)
    at typeSync (/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/node_modules/generator-trigen-app/node_modules/path-type/index.js:27:16)
    at globs.concat.map.x (/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/node_modules/generator-trigen-app/node_modules/mem-fs-editor/node_modules/dir-glob/index.js:63:51)
    at Array.map (<anonymous>)
    at Function.module.exports.sync (/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/node_modules/generator-trigen-app/node_modules/mem-fs-editor/node_modules/dir-glob/index.js:63:33)
    at glob (/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/node_modules/generator-trigen-app/node_modules/mem-fs-editor/node_modules/globby/index.js:77:28)
    at Array.map (<anonymous>)
    at globTasks.reduce (/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/node_modules/generator-trigen-app/node_modules/mem-fs-editor/node_modules/globby/index.js:131:50)
    at Array.reduce (<anonymous>)
    at Function.module.exports.sync (/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/node_modules/generator-trigen-app/node_modules/mem-fs-editor/node_modules/globby/index.js:130:26)
    at EditionInterface.exports.copy (/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/node_modules/generator-trigen-app/node_modules/mem-fs-editor/lib/actions/copy.js:24:26)
    at GeneratorTrigenFrontend.writing (/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/node_modules/generator-trigen-app/generators/app/index.js:621:13)
    at Object.<anonymous> (/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/node_modules/generator-trigen-app/node_modules/yeoman-generator/lib/index.js:427:27)
    at /Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/node_modules/generator-trigen-app/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/node_modules/generator-trigen-app/node_modules/run-async/index.js:24:19
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/node_modules/generator-trigen-app/node_modules/yeoman-generator/lib/index.js:436:22)
    at processImmediate (timers.js:637:19)
```

at 

```js
// files = [ '/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/weather/.trigen-template/TrigenSoftware-weather-711cd3e/.storybook/**/*',
// '/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/weather/.trigen-template/TrigenSoftware-weather-711cd3e/.*',
// '/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/weather/.trigen-template/TrigenSoftware-weather-711cd3e/**/*',
// '!/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/weather/.trigen-template/TrigenSoftware-weather-711cd3e/README.md',
// '!/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/weather/.trigen-template/TrigenSoftware-weather-711cd3e/yarn.lock',
// '!/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/weather/.trigen-template/TrigenSoftware-weather-711cd3e/package.json',
// '!/Users/dangreen/github/generator-trigen-frontend/test/integration/sandbox/weather/.trigen-template/TrigenSoftware-weather-711cd3e/src/manifest.json' ]

this.fs.copy(files, this.destinationRoot());
```

```
"yeoman-generator": "^4.0.1",
"yo": "2.0.6"
```

**Comment by SBoudrias** [comment]
What is "files"?

**Comment by eddiemonge** [comment]
Closing due to inactivity. If this is still an issue please let us know
