### ISSUE TITLE
Yeoman assert.file looks in repository root instead of wherever test helper puts files

### ISSUE THREAD

**Issue by splatteredbits** [yeoman/yeoman#1713]
I've got a test for my template that is looking in my repository's root directory for a file. The test looks like:

```
const path = require('path');
const assert = require('yeoman-assert');
const helpers = require('yeoman-test');

describe('generator-fubar:app', () => {
	beforeAll(() => helpers
		.run(path.join(__dirname, '../generators/app'))
		.withArguments(['Fubar Snafu', 'FubarSnafu', 'The "Fubar Snafu" doesn\'t do anything.']));

	it('creates files', () => {
            assert.file('FubarSnafu.xml'); // <!-- fails
	});
});
```

My generator:

```
const Generator = require('yeoman-generator');
const chalk = require('chalk');
const yosay = require('yosay');

module.exports = class extends Generator {
	prompting () {
		// Have Yeoman greet the user.
		this.log(
			yosay(`Welcome to the terrific ${chalk.red('generator-fubar')} generator!`)
		);

		this.argument('arg1', { type: String, required: true });
		this.argument('arg2', { type: String, required: true });
	}

	writing () {
		this.fs.copyTpl(
			this.templatePath('source.xml'),
			this.destinationPath(`${this.options.arg2}.xml`),
			{
			}
		);
	}
};
```

The test fails becuse `FubarSnafu.xml` doesn't exist. If I create a `FubarSnafu.xml` in the root of my repository, the test passes.

How do I get `assert.file` to look where the Yeoman helper is putting generated files?

```
Node 10.15.1
NPM: 6.4.1
Windows 10
    "yeoman-generator": "^2.0.1",
    "yosay": "^2.0.1"
    "yeoman-assert": "^3.1.0",
    "yeoman-test": "^1.7.0"
```

**Comment by SBoudrias** [comment]
Our unit testing documentation has information on how to get and handle test paths. You can refer to it here: https://yeoman.io/authoring/testing.html

**Comment by splatteredbits** [comment]
This doesn't work. If I do this:

```
describe('generator:app', () => {
	it('creates files', () => {
		helpers
			.run(path.join(__dirname, '../generators/app'))
			.withArguments(['Fubar Snafu', 'FubarSnafu', 'The "Fubar Snafu" doesn\'t do anything.'])
			.then(() => {
				assert.file(['.gitignore', 'Fubar Snafu.xml', 'schtasks.json', 'whiskey.yml', 'WhsEnvironments.json']);
				assert.fileContent('whiskey.yml', /BuildMasterApplicationName: Fubar Snafu/);
				assert.fileContent('whiskey.yml', /Name: FubarSnafu/);
				assert.fileContent('whiskey.yml', /Description: The "Fubar Snafu" scheduled task doesn't do anything\./);
				assert.fileContent('schtasks.json', /"TaskXmlPath": "Fubar Snafu.xml"/);
				assert.fileContent('Fubar Snafu.xml', /<Date>\d\d\d\d-\d\d-\d\dT\d\d:\d\d:\d\d\.\d\d\dZ<\/Date>/);
			});
	});
```
The tests _pass_ but I see an exception stack trace in the output. My NPM task returns a 0 exit code:

```
> generator@0.2.1 test C:\Build\generator
> jest

 PASS  __tests__/app.js (6.836s)
  generator:app
    √ creates files (7ms)
    √ validates the package name  (743ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        7.174s
Ran all test suites.
(node:17628) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Fubar Snafu.xml, no such file or directory
    at convertArgs.forEach.file (C:\Build\generator\node_modules\yeoman-assert\index.js:56:12)
    at Array.forEach (<anonymous>)
    at Function.Object.<anonymous>.assert.file (C:\Build\generator\node_modules\yeoman-assert\index.js:54:26)
    at file (C:\Build\generator\__tests__\app.js:12:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When I return the promise (I think?), I'm back to the old behavior of looking in the root directory for files.

**Comment by SBoudrias** [comment]
You can refer to generator-node tests: https://github.com/yeoman/generator-node/blob/master/__tests__/app.js

You do need to return the promise. And within the `then` you should be in the right folder; unless the root was changed automatically because of a `.yo-rc.json` in a parent directory (like in your home directory?) Any chance this is what would break the expectations here?
