### ISSUE TITLE
--help throws TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by jedmao** [yeoman/yeoman#1717]
## Bug

Running `yo [generator-name] --help` throws a `TypeError`:

```bash
/Users/.../node_modules/yeoman-generator/lib/actions/help.js:68
  name = name.replace(/^yeoman:/, '');
              ^

TypeError: Cannot read property 'replace' of undefined
    at module.exports.help.usage (/Users/.../node_modules/yeoman-generator/lib/actions/help.js:68:15)
    at module.exports.help.help (/Users/.../node_modules/yeoman-generator/lib/actions/help.js:23:36)
    at Environment.run (/Users/jemao/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:474:36)
    at env.lookup (/Users/jemao/.nvm/versions/node/v10.16.0/lib/node_modules/yo/lib/cli.js:167:11)
    at Environment.resolver.lookup (/Users/jemao/.nvm/versions/node/v10.16.0/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:59:12)
    at init (/Users/jemao/.nvm/versions/node/v10.16.0/lib/node_modules/yo/lib/cli.js:128:7)
    at pre (/Users/jemao/.nvm/versions/node/v10.16.0/lib/node_modules/yo/lib/cli.js:87:3)
    at Object.<anonymous> (/Users/jemao/.nvm/versions/node/v10.16.0/lib/node_modules/yo/lib/cli.js:216:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

## Work-around

Manually adding a namespace to my generator of `yeoman:[generator-name]` resolves the issue:

```js
	public constructor(args, opts = {}) {
		this.options.namespace = 'yeoman:xxx';
```

**Comment by SBoudrias** [comment]
Hey @jedmao, is this really happening with all generators? I cannot reproduce with `yo node --help`

Which generator is this throwing for?

**Comment by jedmao** [comment]
I suppose it's possible this is only happening with TypeScript generators? The one that's failing for me is generator-tsx. See [this line](https://github.com/adobe/generator-tsx/blob/ff9fc66aeadb84881794a81794ad46901d4b2683/generators/app/index.ts#L45) for the work-around.

**Comment by jedmao** [comment]
I can't say for sure, but we can close this for now until someone else chimes in later.
