### ISSUE TITLE
Challenges to use yo command when the root-folder has spaces or parentheses

### ISSUE THREAD

**Issue by truls1502** [yeoman/yeoman#1718]
I have posted an issue that I have problem with Particle that using the command `npm run new` - the `new`-script is using `yo`-command.

If you want, you can read the issue at https://github.com/phase2/particle/issues/583
> I am mac users and using Dropbox business account to store my works. I would like to work directly on Dropbox instead of on local then move the folder thereafter.
> 
> The challenge is that the folder name of Dropbox is such as `Dropbox (Company name)`. When I am trying to create a component. 
> 
> I am using Particle: 10.2.1
> ```
> Truls-MBP:~ truls1502$ ln -s '/Users/truls1502/Dropbox (SignWo AS)/git' git           
> Truls-MBP:~ truls1502$ cd git/projects/websitename/web/themes/custom/particle
> Truls-MBP:particle truls1502$ pwd
> /Users/truls1502/git/projects/websitename/web/themes/custom/particle
> 
> Truls-MBP:particle truls1502$ npm run new
> 
> > particle@10.2.1 new /Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle
> > yo ./tools/new-component/index.js
> 
> Hi! This will help you build a component folder with assets.
>       Templates for this are in: tools/new-component
> ? To which design system would you like to add this new component? default
> ? Where would you like this new component? 03-organisms
> ? Where in here? ./
> ? What shall we name it? testtruls
> events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> 
> AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/tools/new-component/templates/_pattern.scss
>     at EditionInterface.exports.copy (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/node_modules/mem-fs-editor/lib/actions/copy.js:48:3)
>     at EditionInterface.module.exports [as copyTpl] (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:29:8)
>     at generatorAssets.(anonymous function).forEach.file (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/tools/new-component/index.js:132:17)
>     at Array.forEach (<anonymous>)
>     at Object.keys.map.fileType (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/tools/new-component/index.js:131:33)
>     at Array.map (<anonymous>)
>     at module.exports.writing (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/tools/new-component/index.js:130:34)
>     at Object.<anonymous> (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/node_modules/yeoman-generator/lib/index.js:424:27)
>     at /Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/node_modules/run-async/index.js:25:25
>     at new Promise (<anonymous>)
> Emitted 'error' event at:
>     at Immediate.setImmediate (/Users/truls1502/Dropbox (SignWo AS)/git/projects/websitename/web/themes/custom/particle/node_modules/yeoman-generator/lib/index.js:433:22)
>     at runCallback (timers.js:705:18)
>     at tryOnImmediate (timers.js:676:5)
>     at processImmediate (timers.js:658:5)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! particle@10.2.1 new: `yo ./tools/new-component/index.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the particle@10.2.1 new script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/truls1502/.npm/_logs/2019-07-30T11_07_10_428Z-debug.log
> ```
> 
> Is there some workaround?

I do not know if this output will help. In case if you need more information, I am happy to provide more info.
```
Truls-MBP:Particle (Company) truls1502$ ./node_modules/.bin/yo --version && echo $PATH $NODE_PATH && node -e 'console.log(process.platform, process.versions)'
2.0.5
/Users/truls1502/.nvm/versions/node/v10.16.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
darwin { http_parser: '2.8.0',
  node: '10.16.1',
  v8: '6.8.275.32-node.54',
  uv: '1.28.0',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '64',
  nghttp2: '1.34.0',
  napi: '4',
  openssl: '1.1.1c',
  icu: '64.2',
  unicode: '12.1',
  cldr: '35.1',
  tz: '2019a' }
```

**Comment by JoshuaKGoldberg** [comment]
The top few lines in the stack point to https://github.com/sboudrias/mem-fs-editor. So I'll go ahead and transfer this there.

**Comment by JoshuaKGoldberg** [comment]
Or, actually, I don't have permissions to transfer to https://github.com/sboudrias/mem-fs-editor since it's not in this organization. 

So, actually, 👋 @truls1502 - if you're still getting this 5+ years later, I'd suggest posting an isolated reproduction in https://github.com/sboudrias/mem-fs-editor. Cheers! 🎩
