### ISSUE TITLE
Couldn't find the 'yo' binary error when installing

### ISSUE THREAD

**Issue by Ciliane** [yeoman/yeoman#1723]
`npm install -g yo generator-code
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
C:\Users\a\AppData\Roaming\npm\yo-complete -> C:\Users\a\AppData\Roaming\npm\node_modules\yo\lib\completion\index.js
C:\Users\a\AppData\Roaming\npm\yo -> C:\Users\a\AppData\Roaming\npm\node_modules\yo\lib\cli.js

> yo@3.1.0 postinstall C:\Users\a\AppData\Roaming\npm\node_modules\yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

√ No .bowerrc file in home directory
√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ No .yo-rc.json file in home directory
√ Node.js version
{ Error: Couldn't find the 'yo' binary. Make sure it's installed and in your $PATH
    at notFoundError (C:\Users\a\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:8:11)
    at verifyENOENT (C:\Users\a\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (C:\Users\a\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn yo',
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "yo "--version""' }
× yo version
{ Error: Couldn't find the 'yo' binary. Make sure it's installed and in your $PATH
    at notFoundError (C:\Users\a\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:8:11)
    at verifyENOENT (C:\Users\a\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (C:\Users\a\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn yo',
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "yo "--version""' }
√ npm version

Found potential issues on your machine :(
+ yo@3.1.0
+ generator-code@1.2.5
updated 2 packages in 75.256s
`

I was searching for fix but didnt found. Another issue with same name didnt helped me (I tried to  fix system variables, i tried to reinstall node.js)

System variable:
PATH: C:\Program Files\nodejs\
by the way i tried to rename PATH to Path

npm --version:
6.9.0

node --version:
10.16.3

npm prefix --global:
C:\Users\a\AppData\Roaming\npm

Maybe all the problems is just beacuse i didnt reload my PC?

**Comment by Ciliane** [comment]
Now installed, but after i try to run any command it says:

C:\Users\Дом\Documents\aa>yo --help
C:\Users\Дом\AppData\Roaming\npm\node_modules\yo\node_modules\windows-release\node_modules\execa\index.js:347
                throw err;
                ^

Error: Command failed: wmic os get Caption
"wmic" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.


    at makeError (C:\a\Дом\AppData\Roaming\npm\node_modules\yo\node_modules\windows-release\node_modules\execa\index.js:174:9)
    at Function.module.exports.sync (C:\Users\a\AppData\Roaming\npm\node_modules\yo\node_modules\windows-release\node_modules\execa\index.js:338:15)
    at windowsRelease (C:\Users\a\AppData\Roaming\npm\node_modules\yo\node_modules\windows-release\index.js:34:24)
    at osName (C:\Users\a\AppData\Roaming\npm\node_modules\yo\node_modules\os-name\index.js:39:18)
    at new Insight (C:\Users\a\AppData\Roaming\npm\node_modules\yo\node_modules\insight\lib\index.js:37:13)
    at Object.<anonymous> (C:\Users\a\AppData\Roaming\npm\node_modules\yo\lib\cli.js:54:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)


every command says this (except for yo --version)

**Comment by Hriday-Muppidi** [comment]
Hello! @Ciliane  Did you find the solution to this issue?? I've been facing the same issue since two days and couldn't find the solution and I have been pulling my hair to get this solved. Let me know if you solved it and if yes how you solved it.

**Comment by NightmareDiscord** [comment]
Open a command prompt as Administrator then run the command `npm install -g yo generator-code` that worked for me.

**Comment by Ciliane** [comment]
I used to not understand how to change system variables propetly

**Comment by brunotech** [comment]
I can solve this problem on my linux mint following this raisin worked for me

https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md
