### ISSUE TITLE
Manifest Validation Fails "ELIFECYCLE"?

### ISSUE THREAD

**Issue by Buzzardbait** [yeoman/yeoman#1724]
I'm new to Yeoman and trying to build an Excel Taskpane. Using yo, it seems to work but then fails to validate. Something to do with lifecycle but no other clues. Here's the logfile:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'validate' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prevalidate', 'validate', 'postvalidate' ]
5 info lifecycle office-addin-taskpane-js@0.0.1~prevalidate: office-addin-taskpane-js@0.0.1
6 info lifecycle office-addin-taskpane-js@0.0.1~validate: office-addin-taskpane-js@0.0.1
7 verbose lifecycle office-addin-taskpane-js@0.0.1~validate: unsafe-perm in lifecycle true
8 verbose lifecycle office-addin-taskpane-js@0.0.1~validate: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;c:\vba\ExcelTaskpane\project\Office-Addin-TaskPane-JS-yo-office\node_modules\.bin;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Common Files\Roxio Shared\DLLShared\;C:\Program Files (x86)\Common Files\Roxio Shared\DLLShared\;C:\Program Files (x86)\Common Files\Roxio Shared\12.0\DLLShared\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\PuTTY\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin\;C:\Program Files\IVI Foundation\VISA\Win64\Bin\;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Martin\AppData\Local\GitHubDesktop\bin;C:\Users\Martin\AppData\Roaming\npm
9 verbose lifecycle office-addin-taskpane-js@0.0.1~validate: CWD: c:\vba\ExcelTaskpane\project\Office-Addin-TaskPane-JS-yo-office
10 silly lifecycle office-addin-taskpane-js@0.0.1~validate: Args: [ '/d /s /c', 'office-addin-manifest validate manifest.xml' ]
11 silly lifecycle office-addin-taskpane-js@0.0.1~validate: Returned: code: 1  signal: null
12 info lifecycle office-addin-taskpane-js@0.0.1~validate: Failed to exec validate script
13 verbose stack Error: office-addin-taskpane-js@0.0.1 validate: `office-addin-manifest validate manifest.xml`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid office-addin-taskpane-js@0.0.1
15 verbose cwd c:\vba\ExcelTaskpane\project\Office-Addin-TaskPane-JS-yo-office
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "validate"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error office-addin-taskpane-js@0.0.1 validate: `office-addin-manifest validate manifest.xml`
22 error Exit status 1
23 error Failed at the office-addin-taskpane-js@0.0.1 validate script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Buzzardbait** [comment]
No I got totally frustrated trying to use Yo and Node and switched over to Visual Studio Community 19 that does it all in one package. I guess I'll just close this issue. But thanks for your reply.
