### ISSUE TITLE
Couldnt find the'yo' binary 

### ISSUE THREAD

**Issue by Nageshwaris** [yeoman/yeoman#1735]
Getting Error: Couldnt find the 'yo' binary.Make sure its installed and in your $PATH while installing npm yo gulp even though yo installed in the machine

**Comment by S4ERyn** [comment]
{ Error: Couldn't find the 'yo' binary. Make sure it's installed and in your $PATH
    at notFoundError (C:\Users\username\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:8:11)
    at verifyENOENT (C:\Users\username\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (C:\Users\username\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn yo',
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe /s /c "yo "--version""' }

**Comment by UlisesGascon** [comment]
@S4ERyn @Nageshwaris  What versions are you using (Windows, Yeoman, Nodejs, npm)?

**Comment by rstm-sf** [comment]
It seems that similar advice will help in this case: https://github.com/yeoman/yeoman/issues/1716#issuecomment-523305408 or https://github.com/yeoman/yeoman/issues/1716#issuecomment-533704907

The first one helped me

**Comment by Srinu066** [comment]
In mycase node-js 14.23.0v , npm -6*** v,  gulp@4.0.2  gulp-cli@2.3.0yo@latest -g @microsoft/generator-sharepoint@1.14.0 i am also getteng same error please help me out
Error: Couldn't find the `yo` binary. Make sure it's installed and in your $PATH.
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn yo',
  path: 'yo',
  spawnargs: [ '--version' ],
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd: 'yo --version',
  timedOut: false,
  killed: false
}
✔ npm version
