### ISSUE TITLE
Command failed error when running `yo` after update to 3.1.1 on Windows

### ISSUE THREAD

**Issue by kshitijzutshi** [yeoman/yeoman#1748]
After `npm install -g yo generator-code`, I try `yo code` but I get this error, I am just unable to resolve.

### Error Message

```

PS K:\Projects\vscode-extentions> yo code
C:\nvm\v14.15.1\node_modules\yo\node_modules\execa\index.js:347
                throw err;
                ^

Error: Command failed: powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption
'powershell' is not recognized as an internal or external command,
operable program or batch file.


    at makeError (C:\nvm\v14.15.1\node_modules\yo\node_modules\execa\index.js:174:9)
    at Function.module.exports.sync (C:\nvm\v14.15.1\node_modules\yo\node_modules\execa\index.js:338:15)
    at windowsRelease (C:\nvm\v14.15.1\node_modules\yo\node_modules\windows-release\index.js:39:19)
    at osName (C:\nvm\v14.15.1\node_modules\yo\node_modules\os-name\index.js:39:18)
    at new Insight (C:\nvm\v14.15.1\node_modules\yo\node_modules\insight\lib\in    at Object.<anonymous> (C:\nvm\v14.15.1\node_modules\yo\lib\cli.js:54:17)   
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 1,
  stdout: '',
  stderr: "'powershell' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n',
  failed: true,
  signal: null,
  cmd: 'powershell (Get-CimInstance -ClassName Win32_OperatingSystem).caption',  timedOut: false
}
```

### System info

```
PS K:\Projects\vscode-extentions> node -e "console.log(process.platform, process.versions)"                         
win32 {
  node: '14.15.1',
  v8: '8.4.371.19-node.17',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '83',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2020a',
  unicode: '13.0'
}
```

**Comment by qeityx** [comment]
same problem did any one found a solution

**Comment by wly2014** [comment]
same problem

**Comment by wly2014** [comment]
The solution: https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr

**Comment by JoshuaKGoldberg** [comment]
Indeed, this looks like a Windows PATH issue. If it's not, then I suspect it's an issue with [`insight`](https://www.npmjs.com/package/insight) - as it looks from the code like that package. Which was removed from `yo` in https://github.com/yeoman/yo/pull/771. Cheers! 🎩
