### ISSUE TITLE
yo @microsoft/sharepoint with TypeError: lookups.flatMap is not a function

### ISSUE THREAD

**Issue by thb65** [yeoman/yeoman#1750]
After installation of Node v10.16.1 and installation of gulp and yo (Everything looks alright !) it fails on command yo @microsoft/sharepoint with TypeError: lookups.flatMap is not a function

```
C:\Users\MYNAME\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:70
    filePatterns: lookups.flatMap(prefix => [`${prefix}/*/index.ts`, `${prefix}/*/index.js`]),
                          ^

TypeError: lookups.flatMap is not a function
    at Environment.resolver.lookup (C:\Users\MYNAME\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:70:27)
    at init (C:\Users\MYNAME\AppData\Roaming\npm\node_modules\yo\lib\cli.js:130:7)
    at pre (C:\Users\MYNAME\AppData\Roaming\npm\node_modules\yo\lib\cli.js:89:3)
    at Object.<anonymous> (C:\Users\MYNAME\AppData\Roaming\npm\node_modules\yo\lib\cli.js:219:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```
I am a beginner ! Few days ago it worked , then I installed nvm (following a microsoft instruction for client webparts Spfx to swap node v8 to node v10) and then problems started and i uninstalled nvm, node v8 and v10 en reinstalled node v10. The TypeError returns. Perhaps something to do with path ?

I tried also yo sppp and got similar failure

Any idea ? thx

**Comment by ruyadorno** [comment]
it looks like the current **yo** runner you're using is not compatible with the version of **node** you're trying to run with (`yo@4` needs `node >= 12.10.0`)

Try reinstalling a compatible version of the **yo** cli with: `npm install -g yo@3`

**Comment by thb65** [comment]
> it looks like the current **yo** runner you're using is not compatible with the version of **node** you're trying to run with (`yo@4` needs `node >= 12.10.0`)
> 
> Try reinstalling a compatible version of the **yo** cli with: `npm install -g yo@3`

Thanks! - this works for me.
