### ISSUE TITLE
Error on $PATH

### ISSUE THREAD

**Issue by tkrupesh14** [yeoman/yeoman#1754]
npm install --global yo  
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.   
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
C:\Users\PK'S PC\AppData\Roaming\npm\yo -> C:\Users\PK'S PC\AppData\Roaming\npm\node_modules\yo\lib\cli.js
C:\Users\PK'S PC\AppData\Roaming\npm\yo-complete -> C:\Users\PK'S PC\AppData\Roaming\npm\node_modules\yo\lib\completion\index.js

> yo@4.2.0 postinstall C:\Users\PK'S PC\AppData\Roaming\npm\node_modules\yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

√ No .bowerrc file in home directory
√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ No .yo-rc.json file in home directory
√ Node.js version
Error: Couldn't find the 'yo' binary. Make sure it's installed and in your $PATH
    at notFoundError (C:\Users\PK'S PC\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:8:11)
    at verifyENOENT (C:\Users\PK'S PC\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (C:\Users\PK'S PC\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn yo',
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "yo "--version""'
}
× yo version
Error: Couldn't find the 'yo' binary. Make sure it's installed and in your $PATH
    at verifyENOENT (C:\Users\PK'S PC\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:43:16)
    at ChildProcess.cp.emit (C:\Users\PK'S PC\AppData\Roaming\npm\node_modules\yo\node_modules\cross-spawn-async\lib\enoent.js:30:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn yo',
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "yo "--version""'
}
√ npm version

Found potential issues on your machine :(
+ yo@4.2.0
updated 1 package in 58.321s

**I have faced this issue more than 10 times**

Please Solve This

**Comment by JoshuaKGoldberg** [comment]
> ```plaintext
> Error: Couldn't find the 'yo' binary. Make sure it's installed and in your $PATH
> ```

Indeed, it looks like the doctor is asking you to install `yo` globally. https://docs.npmjs.com/downloading-and-installing-packages-globally

If that's not actually the issue, feel free to post more system details -your OS version, what specific commands you've run, what you have installed globally- and we can take a look. Cheers! 🎩
