### ISSUE TITLE
Yeoman for Mac Broken

### ISSUE THREAD

**Issue by mongoose666** [yeoman/yeoman#1767]
When running "yo <generator>" you get:

/usr/local/lib/node_modules/yo/node_modules/macos-release/index.js:27
        const [name, version] = nameMap.get(release);
                                ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/usr/local/lib/node_modules/yo/node_modules/macos-release/index.js:27:26)
    at osName (/usr/local/lib/node_modules/yo/node_modules/os-name/index.js:21:18)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:37:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:54:17)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.10.0

**Comment by mongoose666** [comment]
This is due to 'Ventura' not being supported yet. 

To fix this in the interim the 'namedMap' in '/usr/local/lib/node_modules/yo/node_modules/macos-release/index.js' should be:

const nameMap = new Map([
	[22, ['Ventura', '13']],
	[21, ['Monterey', '12']],
	[20, ['Big Sur', '11']],
	[19, ['Catalina', '10.15']],
	[18, ['Mojave', '10.14']],
	[17, ['High Sierra', '10.13']],
	[16, ['Sierra', '10.12']],
	[15, ['El Capitan', '10.11']],
	[14, ['Yosemite', '10.10']],
	[13, ['Mavericks', '10.9']],
	[12, ['Mountain Lion', '10.8']],
	[11, ['Lion', '10.7']],
	[10, ['Snow Leopard', '10.6']],
	[9, ['Leopard', '10.5']],
	[8, ['Tiger', '10.4']],
	[7, ['Panther', '10.3']],
	[6, ['Jaguar', '10.2']],
	[5, ['Puma', '10.1']]
]);

**Comment by AlexSwensen** [comment]
This is a known issue. [Here](https://github.com/yeoman/yo/issues/753#issuecomment-1302569839) is a link to detailed workaround instructions. 
There are also discussions around a proper fix in that same GitHub issue.

**Comment by mischah** [comment]
Released a fix with [v4.3.1](https://www.npmjs.com/package/yo/v/4.3.1) :octocat:
