### ISSUE TITLE
 yo doctor throws error: Error: Cannot find module 'is-ci'

### ISSUE THREAD

**Issue by Raphael40** [yeoman/yeoman#1773]
Occurring on WSL Ubuntu version 2

Running:
`npm install -g yo generator-code`
Followed by:
`yo doctor`

Yields error:
```node:internal/modules/cjs/loader:1145
  throw err;
  ^

Error: Cannot find module 'is-ci'
Require stack:
- /root/.nvm/versions/node/v21.7.1/lib/node_modules/yo/node_modules/update-notifier/index.js
- /root/.nvm/versions/node/v21.7.1/lib/node_modules/yo/lib/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at lazy (/root/.nvm/versions/node/v21.7.1/lib/node_modules/yo/node_modules/import-lazy/index.js:2:51)
    at /root/.nvm/versions/node/v21.7.1/lib/node_modules/yo/node_modules/import-lazy/index.js:10:11
    at new UpdateNotifier (/root/.nvm/versions/node/v21.7.1/lib/node_modules/yo/node_modules/update-notifier/index.js:46:4)
    at module.exports (/root/.nvm/versions/node/v21.7.1/lib/node_modules/yo/node_modules/update-notifier/index.js:183:25)
    at updateCheck (/root/.nvm/versions/node/v21.7.1/lib/node_modules/yo/lib/cli.js:54:20)
    at Object.<anonymous> (/root/.nvm/versions/node/v21.7.1/lib/node_modules/yo/lib/cli.js:190:1) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.nvm/versions/node/v21.7.1/lib/node_modules/yo/node_modules/update-notifier/index.js',
    '/root/.nvm/versions/node/v21.7.1/lib/node_modules/yo/lib/cli.js'
  ]
}

Node.js v21.7.1
```

Creating a new directory and running:
`npm init -y` 
`npm install -d is-ci`
Does not resolve the issue and returns the same error. 

Running: 
`npm list is-ci`
Returns:
```
vscode-theme@1.0.0 /root/Workspace/Projects/vscode-theme
├── is-ci@3.0.1
└─┬ yo@5.0.0
  └─┬ update-notifier@5.1.0
    └── is-ci@2.0.0
```

Can anyone help me resolve this error so I can generate projects with yeoman. 
Thanks

**Comment by JoshuaKGoldberg** [comment]
🤔 I don't reproduce this locally, but the presence of multiple positive reactions makes me think there is a legit bug that is hitting multiple people.

@Raphael40 / anybody else on this thread: could you please post a minimum reproduction (https://antfu.me/posts/why-reproductions-are-required#how-to-create-a-minimal-reproduction)? I'd like to help but can't without being able to see it in action. Thanks! 🎩

**Comment by JoshuaKGoldberg** [comment]
Oh! This is actually a duplicate of https://github.com/yeoman/yo/issues/785. Lovely. That one has a good bit more users reporting their environments and what's happening, along with some suggested remediations.

I'll go ahead and close this one out. We'll triage https://github.com/yeoman/yo/issues/785 soon. Cheers! 🎩
