### ISSUE TITLE
Grunt Server "Got error listen EADDRINUSE"

### ISSUE THREAD

**Issue by rememberlenny** [yeoman/yeoman#938]
Followed instructions for basic webapp and can't get the server running. 

Started with `yo webapp`, but getting an error every time I run `grunt server`.

Error:

`````` CLI
Running "server" task

Running "clean:server" (clean) task

Running "coffee:dist" (coffee) task
>> Destination not written because compiled files were empty.

Running "compass:server" (compass) task
Nothing to compile. If you're trying to start a new project, you have left off the directory argument.
Run "compass -h" to get help.

Running "livereload-start" task
... Starting Livereload server on 35729 ...

... Uhoh. Got error listen EADDRINUSE ...
Error: listen EADDRINUSE
    at errnoException (net.js:769:11)
    at Server._listen2 (net.js:909:14)
    at listen (net.js:936:10)
    at Server.listen (net.js:985:5)
    at Server.listen (/Users/lkbogdonoff/sites/portfolio/node_modules/grunt-contrib-livereload/node_modules/tiny-lr/lib/server.js:133:15)
    at Object.startLRServer (/Users/lkbogdonoff/sites/portfolio/node_modules/grunt-contrib-livereload/lib/utils.js:21:11)
    at Object.module.exports (/Users/lkbogdonoff/sites/portfolio/node_modules/grunt-contrib-livereload/tasks/livereload.js:44:20)
    at Object.task.registerTask.thisTask.fn (/Users/lkbogdonoff/sites/portfolio/node_modules/grunt/lib/grunt/task.js:78:16)
    at Object.Task.start._running (/Users/lkbogdonoff/sites/portfolio/node_modules/grunt/lib/util/task.js:282:30)
    at Task.runTaskFn (/Users/lkbogdonoff/sites/portfolio/node_modules/grunt/lib/util/task.js:235:24)```

Any thoughts @sindresorhus ?
``````

**Comment by monolithed** [comment]
+1

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:14)
    at listen (net.js:1155:10)
    at net.js:1253:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)
```

**Comment by basilinjoe** [comment]
hay am getting this error ! help me please !

error: Grunt :: Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Agent.Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Agent.Server.listen (net.js:1267:5)
    at Object.start (_debugger_agent.js:20:9)
    at startup (node.js:86:9)
    at node.js:814:3

**Comment by akhayoon** [comment]
Thanks @estace your solution did it for me. Just killed the port and everything worked again.

**Comment by rajanmidd** [comment]
Hey,

I am using grunt cli with npm. I have some number of packages but there is one package named as java from npm (https://www.npmjs.com/package/java).

 When java npm package is installed then grunt is not able to restart the node server on change in file.

So can you please let me know what is the issue of grunt with java npm package or how can I solve this?

I got this error:Error: listen EADDRINUSE" on change in any file.
